{
 "title": "P2P",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "view_by",
    "label": "View by",
    "query": "$tag_host:$tag_bzzkey, $tag_host:$tag_pubkey, $tag_host, $tag_bzzkey,$tag_pubkey"
   },
   { "name": "myinterval", "label": "resolution", "query": "5s,10s,30s,100s" },
   {
    "name": "host",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   },
   {
    "name": "bzzkey",
    "query": "SHOW TAG VALUES WITH KEY = \"bzzkey\""
   },
   {
    "name": "pubkey",
    "query": "SHOW TAG VALUES WITH KEY = \"pubkey\""
   }
  ]
 },
 "panels": [
  { "title": "P2P", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Peer.Send()",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "swarm.peer.send.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Registry Peers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "swarm.registry.peers.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  { "title": "P2P Timers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Peer.Send() timer - 95%ile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "p95([[view_by]])",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "swarm.peer.send_t.span",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Peer.Send() timer - max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.peer.send_t.span",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  { "title": "P2P - PSS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "pss.PssMsg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "swarm.peer.send.*pss.PssMsg.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  { "title": "P2P - Stream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "stream.ChunkDeliveryMsgRetrieval",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "swarm.peer.send.*stream.ChunkDeliveryMsgRetrieval.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "stream.ChunkDeliveryMsgSyncing",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "swarm.peer.send.*stream.ChunkDeliveryMsgSyncing.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "stream.RetrieveRequestMsg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "swarm.peer.send.*stream.RetrieveRequestMsg.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "stream.QuitMsg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "swarm.peer.send.*stream.QuitMsg.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "stream.OfferedHashesMsg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "swarm.peer.send.*stream.OfferedHashesMsg.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "stream.WantedHashesMsg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "swarm.peer.send.*stream.WantedHashesMsg.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "stream.RequestSubscriptionMsg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "swarm.peer.send.*stream.RequestSubscriptionMsg.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "stream.SubscribeMsg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "swarm.peer.send.*stream.SubscribeMsg.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "P2P - Hive",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "network.HandshakeMsg",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "[[view_by]]",
       "groupBy": [
        { "params": [ "$myinterval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "bzzkey" ], "type": "tag" },
        { "params": [ "pubkey" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "swarm.peer.send.*network.HandshakeMsg.count",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
        { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
       ]
      }
     ]
    },
    {
     "title": "network.subPeersMsg",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "[[view_by]]",
       "groupBy": [
        { "params": [ "$myinterval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "bzzkey" ], "type": "tag" },
        { "params": [ "pubkey" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "swarm.peer.send.*network.subPeersMsg.count",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
        { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
       ]
      }
     ]
    },
    {
     "title": "network.peersMsg",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "[[view_by]]",
       "groupBy": [
        { "params": [ "$myinterval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "bzzkey" ], "type": "tag" },
        { "params": [ "pubkey" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "swarm.peer.send.*network.peersMsg.count",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
        { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}