{
 "title": "PSS",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "view_by",
    "label": "View by",
    "query": "$tag_host:$tag_bzzkey, $tag_host:$tag_pubkey, $tag_host, $tag_bzzkey,$tag_pubkey"
   },
   { "name": "myinterval", "label": "resolution", "query": "5s,10s,30s,100s" },
   {
    "name": "host",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   },
   {
    "name": "bzzkey",
    "query": "SHOW TAG VALUES WITH KEY = \"bzzkey\""
   },
   {
    "name": "pubkey",
    "query": "SHOW TAG VALUES WITH KEY = \"pubkey\""
   }
  ]
 },
 "panels": [
  { "title": "All measurements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "addFwdCache counter",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pss.addfwdcache.span",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "addFwdCache timer",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pss.addfwdcache.span",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "PSS send raw timer",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "95% - [[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pss.send.raw.span",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    },
    {
     "alias": "mean - [[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pss.send.raw.span",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "PSS enqueue timer",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "95% - [[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pss.enqueue.span",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    },
    {
     "alias": "mean - [[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pss.enqueue.span",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "PSS executeHandlers timer",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "95% - [[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pss.execute-handlers.span",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    },
    {
     "alias": "mean - [[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pss.execute-handlers.span",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "PSS process timer",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "95% - [[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pss.process.span",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    },
    {
     "alias": "mean - [[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pss.process.span",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "PSS len(outbox)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pss.outbox.len.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "PSS handle outbox timer",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pss.handle.outbox.span",
     "select": [
      [
       { "params": [ "p50" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "PSS handle outbox count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pss.handle.outbox.span",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  }
 ]
}