{
 "title": "Retrieve",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "view_by",
    "label": "View by",
    "query": "$tag_host:$tag_bzzkey, $tag_host:$tag_pubkey, $tag_host, $tag_bzzkey,$tag_pubkey"
   },
   { "name": "myinterval", "label": "resolution", "query": "5s,10s,30s,100s" },
   {
    "name": "host",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   },
   {
    "name": "bzzkey",
    "query": "SHOW TAG VALUES WITH KEY = \"bzzkey\""
   },
   {
    "name": "pubkey",
    "query": "SHOW TAG VALUES WITH KEY = \"pubkey\""
   }
  ]
 },
 "panels": [
  { "title": "P2P", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Retrieve request msgs handled",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "swarm.network.retrieve.handle_retrieve_request_msg.count",
     "query": "SELECT mean(\"value\") FROM \"swarm.network.stream.received_chunks_handled.count\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Chunks handled",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.network.retrieve.received_chunks_handled.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  { "title": "P2P Timers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Retrieve peers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "swarm.network.retrieve.peers.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Request from peers count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.network.retrieve.request_from_peers.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  { "title": "P2P - PSS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Retrieve fails",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.network.retrieve.retrieve_chunks_fail.count",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "chunk delivery by peer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.network.retrieve.chunk.delivery.*.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  { "title": "P2P - Stream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "P2P - Hive",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "network.HandshakeMsg",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "[[view_by]]",
       "groupBy": [
        { "params": [ "$myinterval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "bzzkey" ], "type": "tag" },
        { "params": [ "pubkey" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "swarm.peer.send.*network.HandshakeMsg.count",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
        { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
       ]
      }
     ]
    },
    {
     "title": "network.subPeersMsg",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "[[view_by]]",
       "groupBy": [
        { "params": [ "$myinterval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "bzzkey" ], "type": "tag" },
        { "params": [ "pubkey" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "swarm.peer.send.*network.subPeersMsg.count",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
        { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
       ]
      }
     ]
    },
    {
     "title": "network.peersMsg",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "[[view_by]]",
       "groupBy": [
        { "params": [ "$myinterval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "bzzkey" ], "type": "tag" },
        { "params": [ "pubkey" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "swarm.peer.send.*network.peersMsg.count",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
        { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}