{
 "title": "Runtime",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "view_by",
    "label": "View by",
    "query": "$tag_host:$tag_bzzkey, $tag_host:$tag_pubkey, $tag_host, $tag_bzzkey,$tag_pubkey"
   },
   { "name": "myinterval", "label": "resolution", "query": "5s,10s,30s,100s" },
   {
    "name": "host",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   },
   {
    "name": "bzzkey",
    "query": "SHOW TAG VALUES WITH KEY = \"bzzkey\""
   },
   {
    "name": "pubkey",
    "query": "SHOW TAG VALUES WITH KEY = \"pubkey\""
   }
  ]
 },
 "panels": [
  { "title": "Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.runtime.NumGoroutine.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.runtime.NumThread.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  { "title": "MemStats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "HeapInuse",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swarm.runtime.MemStats.HeapInuse.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  { "title": "GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "NumGC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.runtime.MemStats.NumGC.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  }
 ]
}