{
 "title": "Smoke tests",
 "time": { "from": "2019-01-18T19:37:26.327Z", "to": "2019-01-18T20:37:26.327Z" },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total `upload and sync` runs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "jobs ($tag_host , $tag_version , $tag_filesize kb)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "filesize" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm-smoke.upload-and-sync.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failures `upload and sync`",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "timeout ($tag_version ; $tag_filesize kb)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "filesize" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm-smoke.upload-and-sync.timeout.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "fail ($tag_version ; $tag_filesize kb)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "filesize" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm-smoke.upload-and-sync.fail.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upload time per `upload and sync` in seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "upload-time ($tag_host, $tag_filesize, $tag_version)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "filesize" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "swarm-smoke.upload-and-sync.upload-time.span",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Download time for fetch in `upload and sync`",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "download-time ($tag_host, $tag_filesize, $tag_version)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "filesize" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "swarm-smoke.upload-and-sync.single.fetch-time.span",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total time per `upload and sync` in seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "total-time ($tag_host, $tag_filesize, $tag_version)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "filesize" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "swarm-smoke.upload-and-sync.total-time.span",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  { "title": "HTTP `fetch` traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Connect traces",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "connect done ($tag_filesize , $tag_version)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "filesize" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "swarm-smoke.upload-and-sync.connectdone.span",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DNS traces",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "dns done ($tag_host , $tag_filesize , $tag_version)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "filesize" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "swarm-smoke.upload-and-sync.dnsdone.span",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GotConn traces",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "GotConn ($tag_host, $tag_filesize, $tag_version)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "filesize" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "swarm-smoke.upload-and-sync.gotconn.span",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "WroteRequest traces",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "WroteRequest ($tag_host, $tag_filesize, $tag_version)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "filesize" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "swarm-smoke.upload-and-sync.wroterequest.span",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GotFirstResponseByte traces",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "FirstByte ($tag_host, $tag_filesize, $tag_version)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "filesize" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "swarm-smoke.upload-and-sync.firstbyte.span",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PutIdle traces",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "PutIdle ($tag_host, $tag_filesize, $tag_version)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "filesize" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "swarm-smoke.upload-and-sync.putidle.span",
     "select": [
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "HTTP `upload` traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "DNS start traces",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "dns start ($tag_filesize, $tag_host, $tag_version)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "filesize" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "swarm-smoke.api.client.uploadtar.dnsstart.span",
     "query": "SELECT mean(\"value\") FROM \"swarm-smoke.api.client.uploadtar.dnsstart.span\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DNS done traces",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "dns done ($tag_filesize, $tag_host, $tag_version)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "filesize" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "swarm-smoke.api.client.uploadtar.dnsdone.span",
     "query": "SELECT mean(\"value\") FROM \"swarm-smoke.api.client.uploadtar.dnsdone.span\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GotConn traces",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "got conn ($tag_filesize, $tag_host, $tag_version)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "filesize" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "swarm-smoke.api.client.uploadtar.gotconn.span",
     "query": "SELECT mean(\"value\") FROM \"swarm-smoke.api.client.uploadtar.gotconn.span\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PutIdle traces",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "put idle ($tag_filesize, $tag_host, $tag_version)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "filesize" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "swarm-smoke.api.client.uploadtar.putidle.span",
     "query": "SELECT mean(\"value\") FROM \"swarm-smoke.api.client.uploadtar.putidle.span\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  }
 ]
}