{
 "title": "Smoke tests - sliding window (network capacity)",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total `sliding window` runs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "jobs ($tag_host , $tag_version , $tag_filesize kb)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "filesize" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm-smoke.sliding-window.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total time per `sliding window` in seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "total-time ($tag_host, $tag_filesize, $tag_version)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "filesize" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "swarm-smoke.sliding-window.total-time.span",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network depth `sliding window`",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "jobs ($tag_host , $tag_version , $tag_filesize kb)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "filesize" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm-smoke.sliding-window.network-depth.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upload time in `sliding window`",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "download-time ($tag_host, $tag_filesize, $tag_version)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "filesize" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "swarm-smoke.sliding-window.upload-time.span",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Download time for fetch in `sliding window`",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "download-time ($tag_host, $tag_filesize, $tag_version)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "filesize" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "swarm-smoke.sliding-window.single.fetch-time.span",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP `fetch` traces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connect traces",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "alias": "connect done ($tag_filesize , $tag_version)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "filesize" ], "type": "tag" },
        { "params": [ "version" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "swarm-smoke.upload-and-sync.connectdone.span",
       "select": [
        [
         { "params": [ "p95" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "DNS traces",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "alias": "dns done ($tag_host , $tag_filesize , $tag_version)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "filesize" ], "type": "tag" },
        { "params": [ "version" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "swarm-smoke.upload-and-sync.dnsdone.span",
       "select": [
        [
         { "params": [ "p95" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "GotConn traces",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "alias": "GotConn ($tag_host, $tag_filesize, $tag_version)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "filesize" ], "type": "tag" },
        { "params": [ "version" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "swarm-smoke.upload-and-sync.gotconn.span",
       "select": [
        [
         { "params": [ "p95" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "WroteRequest traces",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "alias": "WroteRequest ($tag_host, $tag_filesize, $tag_version)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "filesize" ], "type": "tag" },
        { "params": [ "version" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "swarm-smoke.upload-and-sync.wroterequest.span",
       "select": [
        [
         { "params": [ "p95" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "GotFirstResponseByte traces",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "alias": "FirstByte ($tag_host, $tag_filesize, $tag_version)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "filesize" ], "type": "tag" },
        { "params": [ "version" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "swarm-smoke.upload-and-sync.firstbyte.span",
       "select": [
        [
         { "params": [ "p95" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "PutIdle traces",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "alias": "PutIdle ($tag_host, $tag_filesize, $tag_version)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "filesize" ], "type": "tag" },
        { "params": [ "version" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "swarm-smoke.upload-and-sync.putidle.span",
       "select": [
        [
         { "params": [ "p99" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP `upload` traces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "DNS start traces",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "alias": "dns start ($tag_filesize, $tag_host, $tag_version)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "filesize" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "version" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "swarm-smoke.api.client.uploadtar.dnsstart.span",
       "query": "SELECT mean(\"value\") FROM \"swarm-smoke.api.client.uploadtar.dnsstart.span\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "p99" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "DNS done traces",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "alias": "dns done ($tag_filesize, $tag_host, $tag_version)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "filesize" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "version" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "swarm-smoke.api.client.uploadtar.dnsdone.span",
       "query": "SELECT mean(\"value\") FROM \"swarm-smoke.api.client.uploadtar.dnsdone.span\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "p99" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "GotConn traces",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "alias": "got conn ($tag_filesize, $tag_host, $tag_version)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "filesize" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "version" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "swarm-smoke.api.client.uploadtar.gotconn.span",
       "query": "SELECT mean(\"value\") FROM \"swarm-smoke.api.client.uploadtar.gotconn.span\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "p99" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "PutIdle traces",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "alias": "put idle ($tag_filesize, $tag_host, $tag_version)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "filesize" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "version" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "swarm-smoke.api.client.uploadtar.putidle.span",
       "query": "SELECT mean(\"value\") FROM \"swarm-smoke.api.client.uploadtar.putidle.span\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "p99" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}