{
 "title": "Smoke tests: PSS",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "raw: total-time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "raw.total-time ($tag_host, $tag_msgbytes, $tag_msgcount, $tag_version)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "msgcount" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "msgbytes" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "swarm-smoke-pss.pss.raw.total-time.span",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "sym: total-time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "sym.total-time ($tag_host, $tag_msgbytes, $tag_msgcount, $tag_version)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "msgcount" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "msgbytes" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "swarm-smoke-pss.pss.sym.total-time.span",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "asym: total-time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "asym.total-time ($tag_host, $tag_msgbytes, $tag_msgcount, $tag_version)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "msgcount" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "msgbytes" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "swarm-smoke-pss.pss.asym.total-time.span",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "raw: success/failure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "success  ($tag_version; $tag_msgcount; $tag_msgbytes)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "msgbytes" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "msgcount" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "swarm-smoke-pss.pss.raw.msgs.success.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "fail  ($tag_version; $tag_msgcount; $tag_msgbytes)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "msgbytes" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "msgcount" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "swarm-smoke-pss.pss.raw.msgs.fail.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "sym: success/failure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "success  ($tag_version; $tag_msgcount; $tag_msgbytes)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "msgbytes" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "msgcount" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "swarm-smoke-pss.pss.sym.msgs.success.count",
     "query": "SELECT sum(\"value\") FROM \"swarm-smoke-pss.pss.sym.msgs.success.count\" WHERE $timeFilter GROUP BY time($__interval), \"msgbytes\", \"version\", \"msgcount\" fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "fail  ($tag_version; $tag_msgcount; $tag_msgbytes)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "msgbytes" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "msgcount" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "swarm-smoke-pss.pss.sym.msgs.fail.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "asym: success/failure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "success  ($tag_version; $tag_msgcount; $tag_msgbytes)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "msgbytes" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "msgcount" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "swarm-smoke-pss.pss.asym.msgs.success.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "fail  ($tag_version; $tag_msgcount; $tag_msgbytes)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "msgbytes" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "msgcount" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "swarm-smoke-pss.pss.asym.msgs.fail.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}