{
 "title": "Upload speed",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total `upload speed` runs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "jobs ($tag_host , $tag_version , $tag_filesize kb)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "filesize" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm-smoke.upload-speed.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failures `upload speed`",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "timeout ($tag_version ; $tag_filesize kb)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "filesize" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "upload-speed.timeout.count",
     "query": "SELECT sum(\"value\") FROM \"swarm-smoke.upload-speed.timeout.count\" WHERE $timeFilter GROUP BY time($__interval), \"filesize\", \"version\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "fail ($tag_version ; $tag_filesize kb)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "filesize" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm-smoke.upload-speed.fail.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total time per `upload speed` in seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "total-time ($tag_host, $tag_filesize, $tag_version)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "filesize" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "swarm-smoke.upload-speed.total-time.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "upload-time ($tag_host, $tag_filesize, $tag_version)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "filesize" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "swarm-smoke.upload-and-sync.upload-time.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP `upload` traces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "DNS start traces",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "alias": "dns start ($tag_filesize, $tag_host, $tag_version)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "filesize" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "version" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "swarm-smoke.api.client.uploadtar.dnsstart.span",
       "query": "SELECT mean(\"value\") FROM \"swarm-smoke.api.client.uploadtar.dnsstart.span\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "p99" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "DNS done traces",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "alias": "dns done ($tag_filesize, $tag_host, $tag_version)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "filesize" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "version" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "swarm-smoke.api.client.uploadtar.dnsdone.span",
       "query": "SELECT mean(\"value\") FROM \"swarm-smoke.api.client.uploadtar.dnsdone.span\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "p99" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "GotConn traces",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "alias": "got conn ($tag_filesize, $tag_host, $tag_version)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "filesize" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "version" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "swarm-smoke.api.client.uploadtar.gotconn.span",
       "query": "SELECT mean(\"value\") FROM \"swarm-smoke.api.client.uploadtar.gotconn.span\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "p99" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "PutIdle traces",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "alias": "put idle ($tag_filesize, $tag_host, $tag_version)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "filesize" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "version" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "swarm-smoke.api.client.uploadtar.putidle.span",
       "query": "SELECT mean(\"value\") FROM \"swarm-smoke.api.client.uploadtar.putidle.span\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "p99" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}