local panels = import '../../lib/panels.libsonnet';
local query = import '../../lib/queries.libsonnet';
local queries = import '../../lib/queries/beekeeper/beekeeper-simulation-retrieval.libsonnet';
panels.dashboard.base(title='Beekeeper Simulation - Retrieval', tags=['beekeper'], panels=[
  panels.row.base(title='Total'),
  panels.stat.base(title='uploaded chunks', description='Total uploaded chunks', targets=[query.base(queries.sum_increase_beekeeper_simulation_retrieval_chunks_uploaded_count),]),
  panels.stat.base(title='not uploaded chunks', description='Total not uploaded chunks', targets=[query.base(queries.sum_increase_beekeeper_simulation_retrieval_chunks_not_uploaded_count),]),
  panels.stat.base(title='synced chunks', description='Total synced chunks', targets=[query.base(queries.sum_increase_beekeeper_simulation_retrieval_tags_synced_count),]),
  panels.stat.base(title='not synced chunks', description='Total not synced chunks', targets=[query.base(queries.sum_increase_beekeeper_simulation_retrieval_tags_not_synced_count),]),
  panels.stat.base(title='downloaded chunks', description='Total downloaded chunks', targets=[query.base(queries.sum_increase_beekeeper_simulation_retrieval_chunks_downloaded_count),]),
  panels.stat.base(title='not downloaded chunks', description='Total not downloaded chunks', targets=[query.base(queries.sum_increase_beekeeper_simulation_retrieval_chunks_not_downloaded_count),]),
  panels.stat.base(title='correctly downloaded chunks', description='Total correctly downloaded chunks', targets=[query.base(queries.sum_increase_beekeeper_simulation_retrieval_chunks_retrieved_count),]),
  panels.stat.base(title='incorrectly downloaded chunks', description='Total incorrectly downloaded chunks', targets=[query.base(queries.sum_increase_beekeeper_simulation_retrieval_chunks_not_retrieved_count),]),
  panels.timeseries.base(title='upload rate', description='Chunk upload rate per node', targets=[query.base(queries.increase_beekeeper_simulation_retrieval_chunks_uploaded_count),]),
  panels.timeseries.base(title='failed upload rate', description='Chunk failed upload rate per node', targets=[query.base(queries.increase_beekeeper_simulation_retrieval_chunks_not_uploaded_count),]),
  panels.timeseries.base(title='sync rate', description='Chunk sync rate per node', targets=[query.base(queries.increase_beekeeper_simulation_retrieval_tags_synced_count),]),
  panels.timeseries.base(title='failed sync rate', description='Chunk failed sync rate per node', targets=[query.base(queries.increase_beekeeper_simulation_retrieval_tags_not_synced_count),]),
  panels.timeseries.base(title='download rate', description='Chunk download rate per node', targets=[query.base(queries.increase_beekeeper_simulation_retrieval_chunks_downloaded_count),]),
  panels.timeseries.base(title='failed download rate', description='Chunk failed download rate per node', targets=[query.base(queries.increase_beekeeper_simulation_retrieval_chunks_not_downloaded_count),]),
  panels.timeseries.base(title='correct download rate', description='Correct chunk download rate per node', targets=[query.base(queries.increase_beekeeper_simulation_retrieval_chunks_retrieved_count),]),
  panels.timeseries.base(title='incorrect download rate', description='Incorrect chunk download rate per node', targets=[query.base(queries.increase_beekeeper_simulation_retrieval_chunks_not_retrieved_count),]),
  panels.heatmap.base(title='upload speed', description='Upload speed', targets=[query.base(queries.increase_beekeeper_simulation_retrieval_chunk_upload_seconds_bucket),]),
  panels.heatmap.base(title='sync speed', description='Sync speed', targets=[query.base(queries.increase_beekeeper_simulation_retrieval_tags_sync_seconds_bucket),]),
  panels.heatmap.base(title='download speed', description='Download speed', targets=[query.base(queries.increase_beekeeper_simulation_retrieval_chunk_download_seconds_bucket),]),
  panels.row.base(title='Node $node'),
  panels.stat.base(title='uploaded chunks', description='Total uploaded chunks', targets=[query.base(queries.sum_increase_beekeeper_simulation_retrieval_chunks_uploaded_count),]),
  panels.stat.base(title='not uploaded chunks', description='Total not uploaded chunks', targets=[query.base(queries.sum_increase_beekeeper_simulation_retrieval_chunks_not_uploaded_count),]),
  panels.stat.base(title='synced chunks', description='Total synced chunks', targets=[query.base(queries.sum_increase_beekeeper_simulation_retrieval_tags_synced_count),]),
  panels.stat.base(title='not synced chunks', description='Total not synced chunks', targets=[query.base(queries.sum_increase_beekeeper_simulation_retrieval_tags_not_synced_count),]),
  panels.stat.base(title='downloaded chunks', description='Total downloaded chunks', targets=[query.base(queries.sum_increase_beekeeper_simulation_retrieval_chunks_downloaded_count),]),
  panels.stat.base(title='not downloaded chunks', description='Total not downloaded chunks', targets=[query.base(queries.sum_increase_beekeeper_simulation_retrieval_chunks_not_downloaded_count),]),
  panels.stat.base(title='correctly downloaded chunks', description='Total correctly downloaded chunks', targets=[query.base(queries.sum_increase_beekeeper_simulation_retrieval_chunks_retrieved_count),]),
  panels.stat.base(title='incorrectly downloaded chunks', description='Total incorrectly downloaded chunks', targets=[query.base(queries.sum_increase_beekeeper_simulation_retrieval_chunks_not_retrieved_count),]),
  panels.timeseries.base(title='upload rate', description='Chunk upload rate', targets=[query.base(queries.increase_beekeeper_simulation_retrieval_chunks_uploaded_count),]),
  panels.timeseries.base(title='failed upload rate', description='Chunk failed upload rate', targets=[query.base(queries.increase_beekeeper_simulation_retrieval_chunks_not_uploaded_count),]),
  panels.timeseries.base(title='sync rate', description='Chunk sync rate', targets=[query.base(queries.increase_beekeeper_simulation_retrieval_tags_synced_count),]),
  panels.timeseries.base(title='failed sync rate', description='Chunk failed sync rate', targets=[query.base(queries.increase_beekeeper_simulation_retrieval_tags_not_synced_count),]),
  panels.timeseries.base(title='download rate', description='Chunk download rate', targets=[query.base(queries.increase_beekeeper_simulation_retrieval_chunks_downloaded_count),]),
  panels.timeseries.base(title='failed download rate', description='Chunk failed download rate', targets=[query.base(queries.increase_beekeeper_simulation_retrieval_chunks_not_downloaded_count),]),
  panels.timeseries.base(title='correct  download rate', description='Correct chunk download rate', targets=[query.base(queries.increase_beekeeper_simulation_retrieval_chunks_retrieved_count),]),
  panels.timeseries.base(title='incorrect download rate', description='Incorrect chunk download rate', targets=[query.base(queries.increase_beekeeper_simulation_retrieval_chunks_not_retrieved_count),]),
])
