{
 "title": "Beekeeper dashboard",
 "tags": [ "beekeeper" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Namespace",
    "query": {
     "query": "label_values(push_time_seconds, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Ping Pong", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ping RTT duration",
   "type": "bargauge",
   "description": "Ping round-trip time duration Gauge.",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "beekeeper_check_pingpong_rtt_duration_seconds{job=\"$job\"}",
     "legendFormat": "{{ node }} -> {{ peer }}"
    }
   ]
  },
  {
   "title": "Ping RTT bucket",
   "type": "heatmap",
   "description": "Ping round-trip time duration Histogram.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "increase(beekeeper_check_pingpong_rtt_seconds_bucket{job=\"$job\"}[1m])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Ping RTT count",
   "type": "stat",
   "description": "Ping round-trip time duration Histogram.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "beekeeper_check_pingpong_rtt_seconds_count{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Ping RTT sum",
   "type": "stat",
   "description": "Ping round-trip time duration Histogram.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "beekeeper_check_pingpong_rtt_seconds_sum{job=\"$job\"}"
    }
   ]
  },
  { "title": "Push Sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Uploaded chunks per node",
   "type": "stat",
   "description": "Number of uploaded chunks.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "beekeeper_check_pushsync_chunks_uploaded_count{job=\"$job\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Synced chunks per node",
   "type": "stat",
   "description": "Number of chunks that has been synced with the closest node.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "beekeeper_check_pushsync_chunks_synced_count{job=\"$job\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Not synced chunks per node",
   "type": "stat",
   "description": "Number of chunks that has not been synced with the closest node.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "beekeeper_check_pushsync_chunks_not_synced_count{job=\"$job\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Upload duration",
   "type": "bargauge",
   "description": "Chunk upload duration Gauge.",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "beekeeper_check_pushsync_chunk_upload_duration_seconds{job=\"$job\"}",
     "legendFormat": "{{ node }} ( {{ chunk }} )"
    }
   ]
  },
  {
   "title": "Upload bucket",
   "type": "heatmap",
   "description": "Chunk upload duration Histogram.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "rate(beekeeper_check_pushsync_chunk_upload_seconds_bucket{job=\"$job\"}[1m])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Upload count",
   "type": "stat",
   "description": "Chunk upload duration Histogram.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "beekeeper_check_pushsync_chunk_upload_seconds_count{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Upload sum",
   "type": "stat",
   "description": "Chunk upload duration Histogram.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "beekeeper_check_pushsync_chunk_upload_seconds_sum{job=\"$job\"}"
    }
   ]
  },
  { "title": "Retrieval", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Uploaded chunks per node",
   "type": "stat",
   "description": "Number of uploaded chunks.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "beekeeper_check_retrieval_chunks_uploaded_count{job=\"$job\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Downloaded chunks per node",
   "type": "stat",
   "description": "Number of downloaded chunks.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "beekeeper_check_retrieval_chunks_downloaded_count{job=\"$job\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Retrieved chunks per node",
   "type": "stat",
   "description": "Number of chunks that has been retrieved.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "beekeeper_check_retrieval_chunks_retrieved_count{job=\"$job\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Not retrieved chunks per node",
   "type": "stat",
   "description": "Number of chunks that has not been retrieved.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "beekeeper_check_retrieval_chunks_not_retrieved_count{job=\"$job\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Upload duration",
   "type": "bargauge",
   "description": "Chunk upload duration Gauge.",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "beekeeper_check_retrieval_chunk_upload_duration_seconds{job=\"$job\"}",
     "legendFormat": "{{ node }} ( {{ chunk }} )"
    }
   ]
  },
  {
   "title": "Upload bucket",
   "type": "heatmap",
   "description": "Chunk upload duration Histogram.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "rate(beekeeper_check_retrieval_chunk_upload_seconds_bucket{job=\"$job\"}[1m])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Upload count",
   "type": "stat",
   "description": "Chunk upload duration Histogram.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "beekeeper_check_retrieval_chunk_upload_seconds_count{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Upload sum",
   "type": "stat",
   "description": "Chunk upload duration Histogram.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "beekeeper_check_retrieval_chunk_upload_seconds_sum{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Download duration",
   "type": "bargauge",
   "description": "Chunk download duration Gauge.",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "beekeeper_check_retrieval_chunk_download_duration_seconds{job=\"$job\"}",
     "legendFormat": "{{ node }} ( {{ chunk }} )"
    }
   ]
  },
  {
   "title": "Bucket",
   "type": "heatmap",
   "description": "Chunk download duration Histogram.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "rate(beekeeper_check_retrieval_chunk_download_seconds_bucket{job=\"$job\"}[1m])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Download count",
   "type": "stat",
   "description": "Chunk download duration Histogram.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "beekeeper_check_retrieval_chunk_download_seconds_count{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Download sum",
   "type": "stat",
   "description": "Chunk download duration Histogram.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "beekeeper_check_retrieval_chunk_download_seconds_sum{job=\"$job\"}"
    }
   ]
  }
 ]
}