{
 "title": "Beekeeper Simulation - Retrieval",
 "tags": [
  "bee",
  "beekeeper"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "run",
    "query": {
     "query": "label_values(beekeeper_simulation_retrieval_chunks_uploaded_count, run)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(beekeeper_simulation_retrieval_chunks_downloaded_count{run =~\"$run\"}, node)"
    }
   },
   {
    "name": "resolution",
    "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "uploaded chunks",
   "type": "stat",
   "description": "Total uploaded chunks",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(beekeeper_simulation_retrieval_chunks_uploaded_count{run=~\"$run\"}[$__range]))"
    }
   ]
  },
  {
   "title": "not uploaded chunks",
   "type": "stat",
   "description": "Total not uploaded chunks",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(beekeeper_simulation_retrieval_chunks_not_uploaded_count{run=~\"$run\"}[$__range]))"
    }
   ]
  },
  {
   "title": "synced chunks",
   "type": "stat",
   "description": "Total synced chunks",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(beekeeper_simulation_retrieval_tags_synced_count{run=~\"$run\"}[$__range]))"
    }
   ]
  },
  {
   "title": "not synced chunks",
   "type": "stat",
   "description": "Total not synced chunks",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(beekeeper_simulation_retrieval_tags_not_synced_count{run=~\"$run\"}[$__range]))"
    }
   ]
  },
  {
   "title": "downloaded chunks",
   "type": "stat",
   "description": "Total downloaded chunks",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(beekeeper_simulation_retrieval_chunks_downloaded_count{run=~\"$run\"}[$__range]))"
    }
   ]
  },
  {
   "title": "not downloaded chunks",
   "type": "stat",
   "description": "Total not downloaded chunks",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(beekeeper_simulation_retrieval_chunks_not_downloaded_count{run=~\"$run\"}[$__range]))"
    }
   ]
  },
  {
   "title": "correctly downloaded chunks",
   "type": "stat",
   "description": "Total correctly downloaded chunks",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(beekeeper_simulation_retrieval_chunks_retrieved_count{run=~\"$run\"}[$__range]))"
    }
   ]
  },
  {
   "title": "incorrectly downloaded chunks",
   "type": "stat",
   "description": "Total incorrectly downloaded chunks",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(beekeeper_simulation_retrieval_chunks_not_retrieved_count{run=~\"$run\"}[$__range]))"
    }
   ]
  },
  {
   "title": "upload rate",
   "type": "graph",
   "description": "Chunk upload rate per node",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(beekeeper_simulation_retrieval_chunks_uploaded_count{run=~\"$run\"}[$resolution])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "failed upload rate",
   "type": "graph",
   "description": "Chunk failed upload rate per node",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(beekeeper_simulation_retrieval_chunks_not_uploaded_count{run=~\"$run\"}[$resolution])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "sync rate",
   "type": "graph",
   "description": "Chunk sync rate per node",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(beekeeper_simulation_retrieval_tags_synced_count{run=~\"$run\"}[$resolution])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "failed sync rate",
   "type": "graph",
   "description": "Chunk failed sync rate per node",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(beekeeper_simulation_retrieval_tags_not_synced_count{run=~\"$run\"}[$resolution])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "download rate",
   "type": "graph",
   "description": "Chunk download rate per node",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(beekeeper_simulation_retrieval_chunks_downloaded_count{run=~\"$run\"}[$resolution])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "failed download rate",
   "type": "graph",
   "description": "Chunk failed download rate per node",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(beekeeper_simulation_retrieval_chunks_not_downloaded_count{run=~\"$run\"}[$resolution])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "correct download rate",
   "type": "graph",
   "description": "Correct chunk download rate per node",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(beekeeper_simulation_retrieval_chunks_retrieved_count{run=~\"$run\"}[$resolution])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "incorrect download rate",
   "type": "graph",
   "description": "Incorrect chunk download rate per node",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(beekeeper_simulation_retrieval_chunks_not_retrieved_count{run=~\"$run\"}[$resolution])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "upload speed",
   "type": "heatmap",
   "description": "Upload speed",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "increase(beekeeper_simulation_retrieval_chunk_upload_seconds_bucket{run=~\"$run\"}[$resolution])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "sync speed",
   "type": "heatmap",
   "description": "Sync speed",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "increase(beekeeper_simulation_retrieval_tags_sync_seconds_bucket{run=~\"$run\"}[$resolution])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "download speed",
   "type": "heatmap",
   "description": "Download speed",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "increase(beekeeper_simulation_retrieval_chunk_download_seconds_bucket{run=~\"$run\"}[$resolution])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  { "title": "Node $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "uploaded chunks",
   "type": "stat",
   "description": "Total uploaded chunks",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(beekeeper_simulation_retrieval_chunks_uploaded_count{run=~\"$run\", node=~\"$node\"}[$__range]))"
    }
   ]
  },
  {
   "title": "not uploaded chunks",
   "type": "stat",
   "description": "Total not uploaded chunks",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(beekeeper_simulation_retrieval_chunks_not_uploaded_count{run=~\"$run\", node=~\"$node\"}[$__range]))"
    }
   ]
  },
  {
   "title": "synced chunks",
   "type": "stat",
   "description": "Total synced chunks",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(beekeeper_simulation_retrieval_tags_synced_count{run=~\"$run\", node=~\"$node\"}[$__range]))"
    }
   ]
  },
  {
   "title": "not synced chunks",
   "type": "stat",
   "description": "Total not synced chunks",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(beekeeper_simulation_retrieval_tags_not_synced_count{run=~\"$run\", node=~\"$node\"}[$__range]))"
    }
   ]
  },
  {
   "title": "downloaded chunks",
   "type": "stat",
   "description": "Total downloaded chunks",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(beekeeper_simulation_retrieval_chunks_downloaded_count{run=~\"$run\", node=~\"$node\"}[$__range]))"
    }
   ]
  },
  {
   "title": "not downloaded chunks",
   "type": "stat",
   "description": "Total not downloaded chunks",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(beekeeper_simulation_retrieval_chunks_not_downloaded_count{run=~\"$run\", node=~\"$node\"}[$__range]))"
    }
   ]
  },
  {
   "title": "correctly downloaded chunks",
   "type": "stat",
   "description": "Total correctly downloaded chunks",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(beekeeper_simulation_retrieval_chunks_retrieved_count{run=~\"$run\", node=~\"$node\"}[$__range]))"
    }
   ]
  },
  {
   "title": "incorrectly downloaded chunks",
   "type": "stat",
   "description": "Total incorrectly downloaded chunks",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(beekeeper_simulation_retrieval_chunks_not_retrieved_count{run=~\"$run\", node=~\"$node\"}[$__range]))"
    }
   ]
  },
  {
   "title": "upload rate",
   "type": "graph",
   "description": "Chunk upload rate",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(beekeeper_simulation_retrieval_chunks_uploaded_count{run=~\"$run\", node=~\"$node\"}[$resolution])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "failed upload rate",
   "type": "graph",
   "description": "Chunk failed upload rate",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(beekeeper_simulation_retrieval_chunks_not_uploaded_count{run=~\"$run\", node=~\"$node\"}[$resolution])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "sync rate",
   "type": "graph",
   "description": "Chunk sync rate",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(beekeeper_simulation_retrieval_tags_synced_count{run=~\"$run\", node=~\"$node\"}[$resolution])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "failed sync rate",
   "type": "graph",
   "description": "Chunk failed sync rate",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(beekeeper_simulation_retrieval_tags_not_synced_count{run=~\"$run\", node=~\"$node\"}[$resolution])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "download rate",
   "type": "graph",
   "description": "Chunk download rate",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(beekeeper_simulation_retrieval_chunks_downloaded_count{run=~\"$run\", node=~\"$node\"}[$resolution])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "failed download rate",
   "type": "graph",
   "description": "Chunk failed download rate",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(beekeeper_simulation_retrieval_chunks_not_downloaded_count{run=~\"$run\", node=~\"$node\"}[$resolution])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "correct  download rate",
   "type": "graph",
   "description": "Correct chunk download rate",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(beekeeper_simulation_retrieval_chunks_retrieved_count{run=~\"$run\", node=~\"$node\"}[$resolution])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "incorrect download rate",
   "type": "graph",
   "description": "Incorrect chunk download rate",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(beekeeper_simulation_retrieval_chunks_not_retrieved_count{run=~\"$run\", node=~\"$node\"}[$resolution])",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}