{
 "title": "SLA",
 "tags": [ "beekeeper" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Namespace",
    "query": {
     "query": "label_values(push_time_seconds, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Network Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Data Durability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Avg chunk download speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "(4*1024)/(increase(beekeeper_check_data_durability_chunk_download_duration_seconds_sum{job=\"$job\"}[$__range])/increase(beekeeper_check_data_durability_chunk_download_duration_seconds_count{job=\"$job\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg file download speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "beekeeper_check_data_durability_file_size_bytes{job=\"$job\"} /((increase(beekeeper_check_data_durability_file_download_duration_seconds_sum{job=\"$job\"}[$__range])/increase(beekeeper_check_data_durability_file_download_duration_seconds_count{job=\"$job\"}[$__range])))",
     "legendFormat": "{{ref}}"
    }
   ]
  },
  {
   "title": "All time chunk retrieval rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(beekeeper_check_data_durability_chunk_download_attempts{job=\"$job\"})/sum(beekeeper_check_data_durability_chunk_download_errors{job=\"$job\"})",
     "legendFormat": "{{ref}}"
    }
   ]
  },
  {
   "title": "All time file retrieval rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(beekeeper_check_data_durability_file_download_attempts{job=\"$job\"})/sum(beekeeper_check_data_durability_file_download_errors{job=\"$job\"})",
     "legendFormat": "{{ref}}"
    }
   ]
  },
  {
   "title": "Chunks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beekeeper_check_data_durability_chunks_count{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total download size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beekeeper_check_data_durability_file_size_bytes{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chunk download attempts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(beekeeper_check_data_durability_chunk_download_attempts{job=\"$job\"}[$__range]))",
     "legendFormat": "{{ref}}"
    }
   ]
  },
  {
   "title": "Chunk download errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(beekeeper_check_data_durability_chunk_download_errors{job=\"$job\"}[$__range]))",
     "legendFormat": "{{ref}}"
    }
   ]
  }
 ]
}