{
 "title": "Agent",
 "tags": [ "storage-incentives" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(bee_info, namespace)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(bee_info{namespace=\"$namespace\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Make Sample (s)",
   "type": "stat",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_storageincentives_reserve_sample_duration{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Neighborhood Selection (24H)",
   "type": "stat",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(bee_storageincentives_neighborhood_selected{namespace=~\"$namespace\", instance=~\"$instance\"}[1d])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Is Playing Error Rate ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bee_storageincentives_win_phase_errors{namespace=~\"$namespace\", instance=~\"$instance\"} / bee_storageincentives_claim_phases{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Claim Win Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bee_storageincentives_claim_phase_errors{namespace=~\"$namespace\", instance=~\"$instance\"} / bee_storageincentives_winner{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Reveal Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bee_storageincentives_reveal_phase_errors{namespace=~\"$namespace\", instance=~\"$instance\"} / bee_storageincentives_reveal_phases{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Commit Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bee_storageincentives_commit_phase_errors{namespace=~\"$namespace\", instance=~\"$instance\"} / bee_storageincentives_commit_phases{namespace=~\"$namespace\", instance=~\"$instance\"} ",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}