{
 "title": "Storage incentives - batch store",
 "tags": [ "storage-incentives" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(bee_info, namespace)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(bee_info{namespace=\"$namespace\"}, instance)"
    }
   },
   { "name": "po", "label": "po", "query": { "query": "label_values(po)" } }
  ]
 },
 "panels": [
  {
   "title": "Available capacity",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "bee_batchstore_available_capacity{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "available capacity (chunks)"
    }
   ]
  },
  {
   "title": "Radius",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "bee_batchstore_radius{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "radius"
    }
   ]
  },
  {
   "title": "Inner/Outer",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "bee_batchstore_inner{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "inner"
    },
    {
     "expr": "bee_batchstore_outer{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "outer"
    }
   ]
  },
  {
   "title": "Available capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "bee_batchstore_available_capacity{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "available capacity (chunks)"
    }
   ]
  },
  {
   "title": "Radius",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "bee_batchstore_radius{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "radius"
    }
   ]
  },
  {
   "title": "Inner/Outer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "bee_batchstore_inner{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "inner"
    },
    {
     "expr": "bee_batchstore_outer{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "outer"
    }
   ]
  }
 ]
}