{
 "title": "PullSync",
 "tags": [ "protocols" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(bee_info, namespace)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(bee_info{namespace=\"$namespace\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "LiveSync Iterations",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(bee_puller_worker_iterations{namespace=~\"$namespace\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "received offers",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(bee_pullsync_chunks_offered{namespace=~\"$namespace\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "LiveSync Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(bee_puller_worker_errors{namespace=~\"$namespace\", instance=~\"$instance\"}[5m])\r\n/\r\nrate(bee_puller_worker_iterations{namespace=~\"$namespace\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Last timestamp of synced bin",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "rate(bee_pullsync_last_received{namespace=~\"$namespace\", instance=~\"$instance\"}[5m])",
     "legendFormat": "bin {{bin}}"
    }
   ]
  },
  {
   "title": "received chunks",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(bee_pullsync_chunks_delivered{namespace=~\"$namespace\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "sent chunks offers",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(bee_pullsync_chunks_sent{namespace=~\"$namespace\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}