{
 "title": "PushSync",
 "tags": [ "protocols" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(bee_info, namespace)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(bee_info{namespace=\"$namespace\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Sending", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "P90 push to peer",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(bee_pushsync_push_peer_time_bucket{namespace=~\"$namespace\"}[10m])) by (instance,le))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Avg push to peer",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (bee_pushsync_push_peer_time_sum{namespace=~\"$namespace\"})\n/\nsum by (instance) (bee_pushsync_push_peer_time_count{namespace=~\"$namespace\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Send chunk seconds - success",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Sec" }
   ],
   "targets": [
    {
     "expr": "bee_pushsync_push_peer_time_sum{namespace=~\"$namespace\", instance=~\"$instance\", status=\"success\"}\n/\nbee_pushsync_push_peer_time_count{namespace=~\"$namespace\", instance=~\"$instance\", status=\"success\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Send chunk seconds - failure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Sec" }
   ],
   "targets": [
    {
     "expr": "bee_pushsync_push_peer_time_sum{namespace=~\"$namespace\", instance=~\"$instance\", status=\"failure\"}\n/\nbee_pushsync_push_peer_time_count{namespace=~\"$namespace\", instance=~\"$instance\", status=\"failure\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "send error %",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "bee_pushsync_total_failed_send_attempts{namespace=~\"$namespace\", instance=~\"$instance\"}\n/\nbee_pushsync_total_send_attempts{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "sent {{instance}}"
    }
   ]
  },
  {
   "title": "sends (chunks/min)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(bee_pushsync_total_send_attempts{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "sent {{instance}}"
    }
   ]
  },
  {
   "title": "Neighborhood Replication Error %",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_pushsync_total_replication_error{namespace=~\"$namespace\", instance=~\"$instance\"} / bee_pushsync_total_replication_attempts{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pusher - Outgoing Errors %",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_pushsync_total_outgoing_errors{namespace=~\"$namespace\", instance=~\"$instance\"}\n/\nbee_pushsync_total_outgoing{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "send error rate %",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_pushsync_total_failed_send_attempts{namespace=~\"$namespace\", instance=~\"$instance\"}\n/\nbee_pushsync_total_send_attempts{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Receiving", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "incoming deliveries (chunks/min)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(bee_pushsync_total_received{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "handler error %",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "bee_pushsync_total_handler_errors{namespace=~\"$namespace\", instance=~\"$instance\"} / bee_pushsync_total_received{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Handler Time Seconds",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Sec" }
   ],
   "targets": [
    {
     "expr": "bee_pushsync_total_handler_time_sum{namespace=~\"$namespace\", instance=~\"$instance\", status=\"failure\"}/bee_pushsync_total_handler_time_count{namespace=~\"$namespace\", instance=~\"$instance\", status=\"failure\"}",
     "legendFormat": "failure {{instance}}"
    },
    {
     "expr": "bee_pushsync_total_handler_time_sum{namespace=~\"$namespace\", instance=~\"$instance\", status=\"success\"}/bee_pushsync_total_handler_time_count{namespace=~\"$namespace\", instance=~\"$instance\", status=\"success\"}",
     "legendFormat": "success {{instance}}"
    }
   ]
  },
  {
   "title": "Handler Replication Error %",
   "type": "stat",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_pushsync_handler_replication_errors{namespace=~\"$namespace\", instance=~\"$instance\"}\n/\nbee_pushsync_handler_replication{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Invalid Stamps  %",
   "type": "stat",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_pushsync_invalid_stamps{namespace=~\"$namespace\", instance=~\"$instance\"}\n/\nbee_pushsync_total_received{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Forwarder %",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_pushsync_forwarder{namespace=~\"$namespace\", instance=~\"$instance\"} / bee_pushsync_total_received{namespace=~\"$namespace\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Storer %",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_pushsync_storer{namespace=~\"$namespace\", instance=~\"$instance\"} / bee_pushsync_total_received{namespace=~\"$namespace\", instance=~\"$instance\"}"
    }
   ]
  }
 ]
}