{
 "title": "Geth",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(geth_chain_head_header, job)"
    }
   },
   {
    "name": "quantile",
    "query": "0.5, 0.75, 0.95, 0.99, 0.999, 0.9999"
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "geth_system_cpu_sysload{job=\"$job\"}",
     "legendFormat": "system"
    },
    {
     "expr": "geth_system_cpu_syswait{job=\"$job\"}",
     "legendFormat": "iowait"
    },
    {
     "expr": "geth_system_cpu_procload{job=\"$job\"}",
     "legendFormat": "geth"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(geth_system_memory_allocs{job=\"$job\"}[1m])",
     "legendFormat": "alloc"
    },
    {
     "expr": "geth_system_memory_used{job=\"$job\"}",
     "legendFormat": "used"
    },
    {
     "expr": "geth_system_memory_held{job=\"$job\"}",
     "legendFormat": "held"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(geth_system_disk_readbytes{job=\"$job\"}[1m])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(geth_system_disk_writebytes{job=\"$job\"}[1m])",
     "legendFormat": "write"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(geth_p2p_ingress{job=\"$job\"}[1m])",
     "legendFormat": "ingress"
    },
    {
     "expr": "rate(geth_p2p_egress{job=\"$job\"}[1m])",
     "legendFormat": "egress"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "geth_p2p_peers{job=\"$job\"}",
     "legendFormat": "peers"
    },
    {
     "expr": "rate(geth_p2p_dials{job=\"$job\"}[1m])",
     "legendFormat": "dials"
    },
    {
     "expr": "rate(geth_p2p_serves{job=\"$job\"}[1m])",
     "legendFormat": "serves"
    }
   ]
  },
  { "title": "Blockchain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Latest header",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "geth_chain_head_header{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Chain head",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geth_chain_head_header{job=\"$job\"}",
     "legendFormat": "header"
    },
    {
     "expr": "geth_chain_head_receipt{job=\"$job\"}",
     "legendFormat": "receipt"
    },
    {
     "expr": "geth_chain_head_block{job=\"$job\"}",
     "legendFormat": "block"
    }
   ]
  },
  {
   "title": "Executable transactions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "geth_txpool_pending{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Transaction pool",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geth_txpool_pending{job=\"$job\"}",
     "legendFormat": "executable"
    },
    {
     "expr": "geth_txpool_queued{job=\"$job\"}",
     "legendFormat": "gapped"
    },
    {
     "expr": "geth_txpool_local{job=\"$job\"}",
     "legendFormat": "local"
    }
   ]
  },
  {
   "title": "Latest receipt",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "geth_chain_head_receipt{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Gapped transactions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "geth_txpool_queued{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Latest block",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "geth_chain_head_block{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Local transactions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "geth_txpool_local{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Block processing",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "geth_chain_execution{job=\"$job\", quantile=\"$quantile\"}",
     "legendFormat": "execution (q=$quantile)"
    },
    {
     "expr": "geth_chain_validation{job=\"$job\", quantile=\"$quantile\"}",
     "legendFormat": "validation (q=$quantile)"
    },
    {
     "expr": "geth_chain_write{job=\"$job\", quantile=\"$quantile\"}",
     "legendFormat": "commit (q=$quantile)"
    },
    {
     "expr": "geth_chain_account_reads{job=\"$job\", quantile=\"$quantile\"}",
     "legendFormat": "account read (q=$quantile)"
    },
    {
     "expr": "geth_chain_account_updates{job=\"$job\", quantile=\"$quantile\"}",
     "legendFormat": "account update (q=$quantile)"
    },
    {
     "expr": "geth_chain_account_hashes{job=\"$job\", quantile=\"$quantile\"}",
     "legendFormat": "account hashe (q=$quantile)"
    },
    {
     "expr": "geth_chain_account_commits{job=\"$job\", quantile=\"$quantile\"}",
     "legendFormat": "account commit (q=$quantile)"
    },
    {
     "expr": "geth_chain_storage_reads{job=\"$job\", quantile=\"$quantile\"}",
     "legendFormat": "storage read (q=$quantile)"
    },
    {
     "expr": "geth_chain_storage_updates{job=\"$job\", quantile=\"$quantile\"}",
     "legendFormat": "storage update (q=$quantile)"
    },
    {
     "expr": "geth_chain_storage_hashes{job=\"$job\", quantile=\"$quantile\"}",
     "legendFormat": "storage hashe (q=$quantile)"
    },
    {
     "expr": "geth_chain_storage_commits{job=\"$job\", quantile=\"$quantile\"}",
     "legendFormat": "storage commit (q=$quantile)"
    }
   ]
  },
  {
   "title": "Transaction propagation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(geth_txpool_valid{job=\"$job\"}[1m])",
     "legendFormat": "valid"
    },
    {
     "expr": "rate(geth_txpool_invalid{job=\"$job\"}[1m])",
     "legendFormat": "invalid"
    },
    {
     "expr": "rate(geth_txpool_underpriced{job=\"$job\"}[1m])",
     "legendFormat": "underpriced"
    },
    {
     "expr": "rate(geth_txpool_pending_discard{job=\"$job\"}[1m])",
     "legendFormat": "executable discard"
    },
    {
     "expr": "rate(geth_txpool_pending_replace{job=\"$job\"}[1m])",
     "legendFormat": "executable replace"
    },
    {
     "expr": "rate(geth_txpool_pending_ratelimit{job=\"$job\"}[1m])",
     "legendFormat": "executable ratelimit"
    },
    {
     "expr": "rate(geth_txpool_pending_nofunds{job=\"$job\"}[1m])",
     "legendFormat": "executable nofunds"
    },
    {
     "expr": "rate(geth_txpool_queued_discard{job=\"$job\"}[1m])",
     "legendFormat": "gapped discard"
    },
    {
     "expr": "rate(geth_txpool_queued_replace{job=\"$job\"}[1m])",
     "legendFormat": "gapped replace"
    },
    {
     "expr": "rate(geth_txpool_queued_ratelimit{job=\"$job\"}[1m])",
     "legendFormat": "gapped ratelimit"
    },
    {
     "expr": "rate(geth_txpool_queued_nofunds{job=\"$job\"}[1m])",
     "legendFormat": "gapped nofunds"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Data rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(geth_eth_db_chaindata_disk_read{job=\"$job\"}[1m])",
     "legendFormat": "leveldb read"
    },
    {
     "expr": "rate(geth_eth_db_chaindata_disk_write{job=\"$job\"}[1m])",
     "legendFormat": "leveldb write"
    },
    {
     "expr": "rate(geth_eth_db_chaindata_ancient_read{job=\"$job\"}[1m])",
     "legendFormat": "ancient read"
    },
    {
     "expr": "rate(geth_eth_db_chaindata_ancient_write{job=\"$job\"}[1m])",
     "legendFormat": "ancient write"
    }
   ]
  },
  {
   "title": "Session totals",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "geth_eth_db_chaindata_disk_read{job=\"$job\"}",
     "legendFormat": "leveldb read"
    },
    {
     "expr": "geth_eth_db_chaindata_disk_write{job=\"$job\"}",
     "legendFormat": "leveldb write"
    },
    {
     "expr": "geth_eth_db_chaindata_ancient_read{job=\"$job\"}",
     "legendFormat": "ancient read"
    },
    {
     "expr": "geth_eth_db_chaindata_ancient_write{job=\"$job\"}",
     "legendFormat": "ancient write"
    }
   ]
  },
  {
   "title": "Storage size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "geth_eth_db_chaindata_disk_size{job=\"$job\"}",
     "legendFormat": "leveldb"
    },
    {
     "expr": "geth_eth_db_chaindata_ancient_size{job=\"$job\"}",
     "legendFormat": "ancient"
    }
   ]
  },
  { "title": "Trie Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Clean cache",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(geth_trie_memcache_clean_read{job=\"$job\"}[1m])",
     "legendFormat": "hit"
    },
    {
     "expr": "rate(geth_trie_memcache_clean_write{job=\"$job\"}[1m])",
     "legendFormat": "miss"
    }
   ]
  },
  {
   "title": "Dirty cache",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(geth_trie_memcache_gc_size{job=\"$job\"}[1m])",
     "legendFormat": "gc"
    },
    {
     "expr": "rate(geth_trie_memcache_flush_size{job=\"$job\"}[1m])",
     "legendFormat": "overflow"
    },
    {
     "expr": "rate(geth_trie_memcache_commit_size{job=\"$job\"}[1m])",
     "legendFormat": "commit"
    }
   ]
  }
 ]
}