{
 "title": "OpenEthereum",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(openethereum_sync_status, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Highest block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "openethereum_sync_blocks_highest{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Earliest non pruned state",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "openethereum_prunning_earliest_state{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Sync status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "openethereum_sync_status{job=\"$job\"}\n"
    }
   ]
  },
  {
   "title": "RPC Metrics Reponse time",
   "type": "graph",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "clockms" } },
   "yaxes": [
    { "format": "clockms" }
   ],
   "targets": [
    {
     "expr": "openethereum_metrics_time{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Block/s",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(openethereum_import_blocks{job=\"$job\"}[1m])"
    }
   ]
  },
  {
   "title": "MGas/s",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(openethereum_import_gas{job=\"$job\"}[1m])/1000000"
    }
   ]
  },
  {
   "title": "Tx/s",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(openethereum_import_txs{job=\"$job\"}[1m])"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openethereum_net_peers{job=\"$job\"}",
     "legendFormat": "peers"
    },
    {
     "expr": "openethereum_net_active_peers{job=\"$job\"}",
     "legendFormat": "active_peers"
    }
   ]
  },
  {
   "title": "DB IO",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_reads_bytes_total{container=\"openethereum\"}[1m])",
     "legendFormat": "reads"
    },
    {
     "expr": "rate(container_fs_writes_bytes_total{container=\"openethereum\"}[1m])",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "Queue",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openethereum_queue_size_unverified{job=\"$job\"}",
     "legendFormat": "unverified"
    },
    {
     "expr": "openethereum_queue_size_verified{job=\"$job\"}",
     "legendFormat": "verified"
    },
    {
     "expr": "openethereum_queue_size_verifying{job=\"$job\"}",
     "legendFormat": "verifying"
    }
   ]
  },
  {
   "title": "Pending Snapshot download",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openethereum_snapshot_download_chunks{job=\"$job\"} - openethereum_snapshot_download_chunks_done{job=\"$job\"}",
     "legendFormat": "Pending blocks"
    },
    {
     "expr": "rate(openethereum_snapshot_download_chunks_done{job=\"$job\"}[5m])*3600",
     "legendFormat": "Rate per hour"
    }
   ]
  },
  {
   "title": "Snapshot restore",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openethereum_snapshot_restore_block{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Snapshot GAP",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openethereum_chain_block{job=\"$job\"} - openethereum_chain_warpsync_gap_last{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Snapshot create",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openethereum_snapshot_create_block{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Blockchain cache",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "openethereum_blockchaincache_block_details{job=\"$job\"}",
     "legendFormat": "block_details"
    },
    {
     "expr": "openethereum_blockchaincache_block_recipts{job=\"$job\"}",
     "legendFormat": "block_recipts"
    },
    {
     "expr": "openethereum_blockchaincache_blocks{job=\"$job\"}",
     "legendFormat": "blocks"
    },
    { "expr": "blockchaincache_txaddrs" },
    {}
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "openethereum_queue_mem_used{job=\"$job\"}",
     "legendFormat": "queue"
    }
   ]
  }
 ]
}