{
 "title": "Accounting",
 "tags": [ "components" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(bee_info, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(bee_info{cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "instance",
    "query": "label_values(bee_info{cluster=~\"$cluster\", namespace=~\"$namespace\"}, instance)"
   },
   {
    "name": "interval",
    "query": "1m,5m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(bee_accounting_credit_events_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "credit ({{pod}})"
    },
    {
     "expr": "increase(bee_accounting_debit_events_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "debit ({{pod}})"
    }
   ]
  },
  {
   "title": "totals",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_accounting_total_credited_amount{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "credited ({{pod}})"
    },
    {
     "expr": "bee_accounting_total_debited_amount{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "debited ({{pod}})"
    }
   ]
  },
  {
   "title": "available balance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "bee_swap_available_balance{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "accounting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "increase(bee_accounting_accounting_blocks_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "blocks ({{pod}})"
    },
    {
     "expr": "increase(bee_accounting_accounting_disconnects_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "disconnects ({{pod}})"
    }
   ]
  },
  {
   "title": "disconnects_reconnect_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "increase(bee_accounting_disconnects_reconnect_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "debit ({{pod}})"
    }
   ]
  },
  {
   "title": "disconnects_enforce_refresh_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "increase(bee_accounting_disconnects_enforce_refresh_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "credit ({{pod}})"
    }
   ]
  },
  {
   "title": "ghost_overdraw_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "increase(bee_accounting_disconnects_ghost_overdraw_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "debit ({{pod}})"
    }
   ]
  },
  {
   "title": "disconnects_overdraw_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "increase(bee_accounting_disconnects_overdraw_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "debit ({{pod}})"
    }
   ]
  },
  {
   "title": "refreshment_below_expected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "increase(bee_accounting_refreshment_below_expected{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "debit ({{pod}})"
    }
   ]
  },
  {
   "title": "refreshment_above_expected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "increase(bee_accounting_refreshment_above_expected{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "debit ({{pod}})"
    }
   ]
  },
  {
   "title": "time_out_of_sync_recent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "increase(bee_accounting_time_out_of_sync_recent{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "debit ({{pod}})"
    }
   ]
  },
  {
   "title": "time_out_of_sync_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "increase(bee_accounting_time_out_of_sync_interval{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "debit ({{pod}})"
    }
   ]
  },
  {
   "title": "time_out_of_sync_alleged",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "increase(bee_accounting_time_out_of_sync_alleged{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "debit ({{pod}})"
    }
   ]
  }
 ]
}