{
 "title": "Aggregator",
 "tags": [ "components" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(bee_info, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(bee_info{cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "instance",
    "query": "label_values(bee_info{cluster=~\"$cluster\", namespace=~\"$namespace\"}, instance)"
   },
   {
    "name": "interval",
    "query": "1m,5m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Bee versions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bee_info{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Go versions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_info{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Kademlia inbound connections",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_kademlia_total_inbound_connections{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{job=\"kube-state-metrics\",cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",container=~\"bee\"}"
    }
   ]
  },
  {
   "title": "Kademlia outbound connections",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_kademlia_total_outbound_connections{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Kademlia Depth",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bee_kademlia_current_depth{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "depth {{instance}}"
    }
   ]
  },
  {
   "title": "Kademlia Radius",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bee_kademlia_current_radius{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "depth {{instance}}"
    }
   ]
  },
  {
   "title": "Kademlia known peers",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bee_kademlia_currently_known_peers{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "depth {{instance}}"
    }
   ]
  },
  {
   "title": "Kademlia connected peers",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bee_kademlia_currently_connected_peers{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "depth {{instance}}"
    }
   ]
  }
 ]
}