{
 "title": "API",
 "tags": [ "components" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(bee_info, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(bee_info{cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "instance",
    "query": "label_values(bee_info{cluster=~\"$cluster\", namespace=~\"$namespace\"}, instance)"
   },
   {
    "name": "interval",
    "query": "1m,5m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "api request rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(bee_api_ping_request_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "api_ping_request_rate ({{pod}})"
    },
    {
     "expr": "increase(bee_api_request_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "api_request_rate ({{pod}})"
    }
   ]
  },
  {
   "title": "Upload api duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "bee_api_content_api_duration_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",method=\"POST\"}/bee_api_content_api_duration_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",method=\"POST\"}",
     "legendFormat": "{{filesize}} bytes {{instance}}"
    }
   ]
  },
  {
   "title": "Download api duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "bee_api_content_api_duration_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",method=\"GET\"}/bee_api_content_api_duration_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",method=\"GET\"}",
     "legendFormat": "{{filesize}} bytes {{instance}}"
    }
   ]
  },
  {
   "title": "response duration seconds",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bee_api_response_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "response codes (2XX)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "increase(bee_api_response_code_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",code=~\"2..\"}[$interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "response codes (3XX)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "increase(bee_api_response_code_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",code=~\"3..\"}[$interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "response codes (4XX)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "increase(bee_api_response_code_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",code=~\"4..\"}[$interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "response codes (5XX)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "increase(bee_api_response_code_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",code=~\"5..\"}[$interval])",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}