{
 "title": "Bee (Namespace)",
 "tags": [ "components" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(bee_info, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(bee_info{cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "instance",
    "query": "label_values(bee_info{cluster=~\"$cluster\", namespace=~\"$namespace\"}, instance)"
   },
   {
    "name": "interval",
    "query": "1m,5m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Headlines", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "libp2p created connection per bee node",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bee_libp2p_created_connection_count{namespace=\"$namespace\"})/count(bee_libp2p_created_connection_count{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "libp2p handled connection per bee node",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bee_libp2p_handled_connection_count{namespace=\"$namespace\"})/count(bee_libp2p_handled_connection_count{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "average uptime per bee node",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(time()-bee_process_start_time_seconds{namespace=\"$namespace\"})/count(bee_process_start_time_seconds{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "average restarts per bee node",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"$namespace\",container=\"bee\"})/count(kube_pod_container_status_restarts_total{namespace=\"$namespace\",container=\"bee\"})"
    }
   ]
  },
  {
   "title": "bee version (bee-0)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_info{namespace=\"$namespace\",pod=\"bee-0\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "go version (bee-0)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_info{namespace=\"$namespace\",pod=\"bee-0\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 25 } },
  {
   "title": "error logs increase over 1h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "increase(bee_log_error_count{namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(bee_log_trace_count{namespace=\"$namespace\"})by(pod)"
    },
    {
     "expr": "sum(bee_log_debug_count{namespace=\"$namespace\"})by(pod)"
    },
    {
     "expr": "sum(bee_log_info_count{namespace=\"$namespace\"})by(pod)"
    },
    {
     "expr": "sum(bee_log_warn_count{namespace=\"$namespace\"})by(pod)"
    },
    {
     "expr": "sum(bee_log_error_count{namespace=\"$namespace\"})by(pod)"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 34 } },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 35 } },
  {
   "title": "api requests increase over 1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "increase(bee_api_request_count{namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "api",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum(bee_api_response_duration_seconds_sum{namespace=\"$namespace\"})by(pod)/sum(bee_api_response_duration_seconds_count{namespace=\"$namespace\"})by(pod)"
    },
    {
     "expr": "sum(bee_api_request_count{namespace=\"$namespace\"})by(pod)"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 44 } },
  { "title": "Runtime", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 45 } },
  {
   "title": "goroutines increase over 1h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "increase(go_goroutines{namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "gc cpu fraction increase over 1h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "increase(go_memstats_gc_cpu_fraction{namespace=\"$namespace\"}[$interval])",
     "legendFormat": "({{pod}})"
    }
   ]
  },
  {
   "title": "runtime",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum(go_goroutines{namespace=\"$namespace\"})by(pod)"
    },
    {
     "expr": "sum(go_memstats_gc_cpu_fraction{namespace=\"$namespace\"})by(pod)"
    },
    {
     "expr": "sum(go_gc_duration_seconds_count{namespace=\"$namespace\"})by(pod)"
    }
   ]
  },
  { "title": "Accounting", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 12, "y": 62 } },
  { "title": "Retrieval", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 63 } }
 ]
}