{
 "title": "Bee",
 "tags": [ "components" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(bee_info, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(bee_info{cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "instance",
    "query": "label_values(bee_info{cluster=~\"$cluster\", namespace=~\"$namespace\"}, instance)"
   },
   {
    "name": "interval",
    "query": "1m,5m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "libp2p created connection",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_libp2p_created_connection_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "libp2p handled connection",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_libp2p_handled_connection_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-bee_process_start_time_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "restarts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{job=\"kube-state-metrics\",cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",container=~\"bee\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "bee version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_info{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "reachability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_kademlia_reachability_status{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "go version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_info{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "panics (last 24h)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}|=\"panic\"[$interval]))by(pod)"
    }
   ]
  },
  {
   "title": "log messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bee_log_log_trace_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "traces ({{pod}})"
    },
    {
     "expr": "increase(bee_log_debug_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "debug ({{pod}})"
    },
    {
     "expr": "increase(bee_log_info_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "info ({{pod}})"
    },
    {
     "expr": "increase(bee_log_warn_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "warn ({{pod}})"
    },
    {
     "expr": "increase(bee_log_error_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "error ({{pod}})"
    }
   ]
  },
  {
   "title": "Storage space capacity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",persistentvolumeclaim=~\"data-$instance\"}",
     "legendFormat": "statestore ({{persistentvolumeclaim}})"
    },
    {
     "expr": "kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",persistentvolumeclaim=~\"localstore-$instance\"}",
     "legendFormat": "localstore ({{persistentvolumeclaim}})"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 40 } },
  {
   "title": "Storage space in use",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",persistentvolumeclaim=~\"data-$instance\"}/kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",persistentvolumeclaim=~\"data-$instance\"}",
     "legendFormat": "statestore ({{persistentvolumeclaim}})"
    },
    {
     "expr": "kubelet_volume_stats_used_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",persistentvolumeclaim=~\"localstore-$instance\"}/kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",persistentvolumeclaim=~\"localstore-$instance\"}",
     "legendFormat": "localstore ({{persistentvolumeclaim}})"
    }
   ]
  },
  { "title": "Runtime", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 12, "y": 49 } },
  {
   "title": "goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "goroutines ({{pod}})"
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "used ({{pod}})"
    },
    {
     "expr": "go_memstats_alloc_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "allocated ({{pod}})"
    }
   ]
  },
  {
   "title": "gc cpu fraction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "go_memstats_gc_cpu_fraction{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "({{pod}})"
    }
   ]
  },
  {
   "title": "gc rate (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "increase(go_gc_duration_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "({{pod}})"
    }
   ]
  }
 ]
}