{
 "title": "Chain calls",
 "tags": [ "components" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(bee_info, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(bee_info{cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "instance",
    "query": "label_values(bee_info{cluster=~\"$cluster\", namespace=~\"$namespace\"}, instance)"
   },
   {
    "name": "interval",
    "query": "1m,5m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Total RPC calls",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_eth_backend_total_rpc_calls{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Calls to eth_blockNumber count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_eth_backend_calls_block_number{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "RPC calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(bee_eth_backend_total_rpc_calls{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "blocklisted_peers({{instance}})"
    }
   ]
  },
  {
   "title": "Get Block Number calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "increase(bee_eth_backend_calls_block_number{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "disconnects({{instance}})"
    }
   ]
  }
 ]
}