{
 "title": "Disk",
 "tags": [ "components" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(bee_info, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(bee_info{cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "instance",
    "query": "label_values(bee_info{cluster=~\"$cluster\", namespace=~\"$namespace\"}, instance)"
   },
   {
    "name": "interval",
    "query": "1m,5m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Capacity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",persistentvolumeclaim=~\"data-$instance\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    },
    {
     "expr": "kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",persistentvolumeclaim=~\"localstore-$instance\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Usage (Localstore)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",persistentvolumeclaim=~\"localstore-$instance\"}/kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",persistentvolumeclaim=~\"localstore-$instance\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Usage StateStore",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",persistentvolumeclaim=~\"data-$instance\"}/kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",persistentvolumeclaim=~\"data-$instance\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}