{
 "title": "Kademlia",
 "tags": [ "components" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(bee_info, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(bee_info{cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "instance",
    "query": "label_values(bee_info{cluster=~\"$cluster\", namespace=~\"$namespace\"}, instance)"
   },
   {
    "name": "interval",
    "query": "1m,5m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "bee_kademlia_current_depth{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Radius",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "bee_kademlia_current_storage_depth{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Flagged for blocking per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(bee_kademlia_flag{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Blocklist due to flagging per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bee_kademlia_blocklist{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Libp2p blocklisting rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(bee_libp2p_blocklisted_peer_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "({{instance}})"
    }
   ]
  },
  {
   "title": "Disconnects rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(bee_kademlia_total_inbound_disconnections{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "({{instance}})"
    }
   ]
  },
  {
   "title": "P99 Ping Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(bee_kademlia_peer_latency_ewma_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval]))by(instance,le))",
     "legendFormat": "({{instance}})"
    },
    {
     "expr": "rate(bee_kademlia_peer_latency_ewma_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])/rate(bee_kademlia_peer_latency_ewma_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])"
    }
   ]
  },
  {
   "title": "Before Expire Waits",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_kademlia_total_before_expire_waits{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "before_expire_waits({{instance}})"
    }
   ]
  },
  {
   "title": "Connection To Bootnodes Attemps",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_kademlia_total_bootnodes_connection_attempts{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "bootnodes_connection_attempts({{instance}})"
    }
   ]
  },
  {
   "title": "Light nodes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_lightnode_currently_connected_peers{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connect/Known",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_kademlia_currently_connected_peers{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "connected({{instance}})"
    },
    {
     "expr": "bee_kademlia_currently_known_peers{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "known({{instance}})"
    }
   ]
  },
  {
   "title": "Metrics Flush Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_kademlia_internal_metrics_flush_total_errors{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "metrics_flush_total_errors({{instance}})"
    }
   ]
  },
  {
   "title": "Pick Calls",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_kademlia_pick_calls{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "pick_calls({{instance}})"
    },
    {
     "expr": "bee_kademlia_pick_calls_false{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "pick_calls_false({{instance}})"
    }
   ]
  },
  {
   "title": "Metrics Flush Time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(bee_kademlia_internal_metrics_flush_time_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval]))by(le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_kademlia_total_inbound_connections{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "inbound({{instance}})"
    },
    {
     "expr": "bee_kademlia_total_inbound_disconnections{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "inbound_disconnections({{instance}})"
    },
    {
     "expr": "bee_kademlia_total_outbound_connections{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "outbound({{instance}})"
    },
    {
     "expr": "bee_kademlia_total_outbound_connection_attempts{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "outbound_attempts({{instance}})"
    },
    {
     "expr": "bee_kademlia_total_outbound_connection_failed_attempts{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "outbound_failed_attempts({{instance}})"
    }
   ]
  },
  {
   "title": "Add Addressbook Overlays Time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(bee_kademlia_start_add_addressbook_overlays_time_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval]))by(le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Connected Peers Reachability",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_kademlia_peers_reachability_status{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}: {{peers_reachability_status}}"
    }
   ]
  }
 ]
}