{
 "title": "Localstore",
 "tags": [ "components" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(bee_info, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(bee_info{cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "instance",
    "query": "label_values(bee_info{cluster=~\"$cluster\", namespace=~\"$namespace\"}, instance)"
   },
   {
    "name": "interval",
    "query": "1m,5m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Sizes", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Reserve size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "bee_localstore_reserve_size{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cache size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "bee_localstore_cache_size{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Reserve Size Within Storage Radius",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "bee_localstore_reserve_size_within_radius{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Invalid Chunks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "bee_localstore_reserve_missing_batch{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Evictions", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 17 } },
  {
   "title": "Storage Radius",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "bee_localstore_storage_radius{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Over capacity triggers (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(bee_localstore_over_cap_trigger_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Eviction count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "bee_localstore_evicted_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Expiration count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "bee_localstore_expired_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Eviction rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "rate(bee_localstore_evicted_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Expiration rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "rate(bee_localstore_expired_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Expired batches processed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_localstore_expired_batch_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 12, "y": 50 } },
  {
   "title": "TX Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(bee_storage_tx_total_duration_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval]))/sum(increase(bee_storage_tx_total_duration_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Reserve Component Methods Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(bee_localstore_method_calls_duration_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",component=\"reserve\"}[$interval]))by(method)/sum(increase(bee_localstore_method_calls_duration_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",component=\"reserve\"}[$interval]))by(method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Reserve Component Methods Call Error Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bee_localstore_method_calls{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",component=\"reserve\",status=\"failure\"})by(method)/sum(bee_localstore_method_calls{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",component=\"reserve\"})by(method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Indexstore Component Methods Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(bee_storage_index_store_calls_duration_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval]))by(method)/sum(increase(bee_storage_index_store_calls_duration_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval]))by(method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexstore Component Methods Call Error Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bee_storage_index_store_calls{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",status=\"failure\"})by(method)/sum(bee_storage_index_store_calls{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"})by(method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Chunkstore Component Methods Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(bee_storage_chunk_store_calls_duration_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval]))by(method)/sum(increase(bee_storage_chunk_store_calls_duration_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval]))by(method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Chunkstore Component Methods Call Error Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bee_storage_chunk_store_calls{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",status=\"failure\"})by(method)/sum(bee_storage_chunk_store_calls{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"})by(method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Cachestore Component Methods Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(bee_localstore_method_calls_duration_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",component=\"cachestore\"}[$interval]))by(method)/sum(increase(bee_localstore_method_calls_duration_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",component=\"cachestore\"}[$interval]))by(method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Cachestore Component Methods Call Error Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bee_localstore_method_calls{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",component=\"cachestore\",status=\"failure\"})by(method)/sum(bee_localstore_method_calls{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",component=\"cachestore\"})by(method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Netstore Component Methods Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(bee_localstore_method_calls_duration_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",component=\"netstore\"}[$interval]))by(method)/sum(increase(bee_localstore_method_calls_duration_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",component=\"netstore\"}[$interval]))by(method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Netstore Component Methods Call Error Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bee_localstore_method_calls{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",component=\"netstore\",status=\"failure\"})by(method)/sum(bee_localstore_method_calls{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",component=\"netstore\"})by(method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Pinstore Component Methods Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(bee_localstore_method_calls_duration_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",component=\"pinstore\"}[$interval]))by(method)/sum(increase(bee_localstore_method_calls_duration_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",component=\"pinstore\"}[$interval]))by(method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Pinstore Component Methods Call Error Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bee_localstore_method_calls{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",component=\"pinstore\",status=\"failure\"})by(method)/sum(bee_localstore_method_calls{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",component=\"pinstore\"})by(method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  { "title": "LevelDB Stats", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 12, "y": 107 } },
  {
   "title": "Write Delay Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "targets": [
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",counter=\"write_delay_count\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Write Delay Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",counter=\"write_delay_duration\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Alive Snapshots",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "targets": [
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",counter=\"alive_snapshots\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Alive Iterators",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
   "targets": [
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",counter=\"alive_iterators\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "IO Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",counter=\"io_read\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "IO Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",counter=\"io_write\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Block Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",counter=\"block_cache_size\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Opened Tables",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 132 },
   "targets": [
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",counter=\"opened_tables_count\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Compaction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 140 },
   "targets": [
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",counter=\"mem_comp\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Level 0 Compaction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 140 },
   "targets": [
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",counter=\"level_0_comp\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Non Level 0 Compaction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 148 },
   "targets": [
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",counter=\"non_level_0_comp\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Seek Compaction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 148 },
   "targets": [
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",counter=\"seek_comp\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Level Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",counter=\"level_0_size\"}[$__rate_interval])",
     "legendFormat": "{{pod}}->{{counter}}"
    },
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",counter=\"level_1_size\"}[$__rate_interval])",
     "legendFormat": "{{pod}}->{{counter}}"
    },
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",counter=\"level_2_size\"}[$__rate_interval])",
     "legendFormat": "{{pod}}->{{counter}}"
    }
   ]
  },
  {
   "title": "Table Count by Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 156 },
   "targets": [
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",counter=\"level_0_tables_count\"}[$__rate_interval])",
     "legendFormat": "{{pod}}->{{counter}}"
    },
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",counter=\"level_1_tables_count\"}[$__rate_interval])",
     "legendFormat": "{{pod}}->{{counter}}"
    },
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",counter=\"level_2_tables_count\"}[$__rate_interval])",
     "legendFormat": "{{pod}}->{{counter}}"
    }
   ]
  },
  {
   "title": "Read by Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",counter=\"level_0_read\"}[$__rate_interval])",
     "legendFormat": "{{pod}}->{{counter}}"
    },
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",counter=\"level_1_read\"}[$__rate_interval])",
     "legendFormat": "{{pod}}->{{counter}}"
    },
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",counter=\"level_2_read\"}[$__rate_interval])",
     "legendFormat": "{{pod}}->{{counter}}"
    }
   ]
  },
  {
   "title": "Write by Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",counter=\"level_0_write\"}[$__rate_interval])",
     "legendFormat": "{{pod}}->{{counter}}"
    },
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",counter=\"level_1_write\"}[$__rate_interval])",
     "legendFormat": "{{pod}}->{{counter}}"
    },
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",counter=\"level_2_write\"}[$__rate_interval])",
     "legendFormat": "{{pod}}->{{counter}}"
    }
   ]
  },
  {
   "title": "Compaction Duration by Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",counter=\"level_0_duration\"}[$__rate_interval])",
     "legendFormat": "{{pod}}->{{counter}}"
    },
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",counter=\"level_1_duration\"}[$__rate_interval])",
     "legendFormat": "{{pod}}->{{counter}}"
    },
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",counter=\"level_2_duration\"}[$__rate_interval])",
     "legendFormat": "{{pod}}->{{counter}}"
    }
   ]
  }
 ]
}