{
 "title": "Beekeeper Simulation - Retrieval",
 "tags": [ "beekeeper" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(bee_info, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(bee_info{cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "instance",
    "query": "label_values(bee_info{cluster=~\"$cluster\", namespace=~\"$namespace\"}, instance)"
   },
   {
    "name": "interval",
    "query": "1m,5m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Total", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "uploaded chunks",
   "type": "stat",
   "description": "Total uploaded chunks",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(beekeeper_simulation_retrieval_chunks_uploaded_count{run=~\"$run\",node=~\"$node\"}[$__range]))"
    }
   ]
  },
  {
   "title": "not uploaded chunks",
   "type": "stat",
   "description": "Total not uploaded chunks",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(beekeeper_simulation_retrieval_chunks_not_uploaded_count{run=~\"$run\",node=~\"$node\"}[$__range]))"
    }
   ]
  },
  {
   "title": "synced chunks",
   "type": "stat",
   "description": "Total synced chunks",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(beekeeper_simulation_retrieval_tags_synced_count{run=~\"$run\",node=~\"$node\"}[$__range]))"
    }
   ]
  },
  {
   "title": "not synced chunks",
   "type": "stat",
   "description": "Total not synced chunks",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(beekeeper_simulation_retrieval_tags_not_synced_count{run=~\"$run\",node=~\"$node\"}[$__range]))"
    }
   ]
  },
  {
   "title": "downloaded chunks",
   "type": "stat",
   "description": "Total downloaded chunks",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(beekeeper_simulation_retrieval_chunks_downloaded_count{run=~\"$run\",node=~\"$node\"}[$__range]))"
    }
   ]
  },
  {
   "title": "not downloaded chunks",
   "type": "stat",
   "description": "Total not downloaded chunks",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(beekeeper_simulation_retrieval_chunks_not_downloaded_count{run=~\"$run\",node=~\"$node\"}[$__range]))"
    }
   ]
  },
  {
   "title": "correctly downloaded chunks",
   "type": "stat",
   "description": "Total correctly downloaded chunks",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(beekeeper_simulation_retrieval_chunks_retrieved_count{run=~\"$run\",node=~\"$node\"}[$__range]))"
    }
   ]
  },
  {
   "title": "incorrectly downloaded chunks",
   "type": "stat",
   "description": "Total incorrectly downloaded chunks",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(beekeeper_simulation_retrieval_chunks_not_retrieved_count{run=~\"$run\",node=~\"$node\"}[$__range]))"
    }
   ]
  },
  {
   "title": "upload rate",
   "type": "timeseries",
   "description": "Chunk upload rate per node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "increase(beekeeper_simulation_retrieval_chunks_uploaded_count{run=~\"$run\",node=~\"$node\"}[$resolution])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "failed upload rate",
   "type": "timeseries",
   "description": "Chunk failed upload rate per node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "increase(beekeeper_simulation_retrieval_chunks_not_uploaded_count{run=~\"$run\",node=~\"$node\"}[$resolution])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "sync rate",
   "type": "timeseries",
   "description": "Chunk sync rate per node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "increase(beekeeper_simulation_retrieval_tags_synced_count{run=~\"$run\",node=~\"$node\"}[$resolution])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "failed sync rate",
   "type": "timeseries",
   "description": "Chunk failed sync rate per node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "increase(beekeeper_simulation_retrieval_tags_not_synced_count{run=~\"$run\",node=~\"$node\"}[$resolution])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "download rate",
   "type": "timeseries",
   "description": "Chunk download rate per node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "increase(beekeeper_simulation_retrieval_chunks_downloaded_count{run=~\"$run\",node=~\"$node\"}[$resolution])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "failed download rate",
   "type": "timeseries",
   "description": "Chunk failed download rate per node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "increase(beekeeper_simulation_retrieval_chunks_not_downloaded_count{run=~\"$run\",node=~\"$node\"}[$resolution])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "correct download rate",
   "type": "timeseries",
   "description": "Correct chunk download rate per node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "increase(beekeeper_simulation_retrieval_chunks_retrieved_count{run=~\"$run\",node=~\"$node\"}[$resolution])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "incorrect download rate",
   "type": "timeseries",
   "description": "Incorrect chunk download rate per node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "increase(beekeeper_simulation_retrieval_chunks_not_retrieved_count{run=~\"$run\",node=~\"$node\"}[$resolution])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "upload speed",
   "type": "heatmap",
   "description": "Upload speed",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(beekeeper_simulation_retrieval_chunk_upload_seconds_bucket{run=~\"$run\"}[$resolution])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "sync speed",
   "type": "heatmap",
   "description": "Sync speed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(beekeeper_simulation_retrieval_tags_sync_seconds_bucket{run=~\"$run\"}[$resolution])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "download speed",
   "type": "heatmap",
   "description": "Download speed",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(beekeeper_simulation_retrieval_chunk_download_seconds_bucket{run=~\"$run\"}[$resolution])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  { "title": "Node $node", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 12, "y": 81 } },
  {
   "title": "uploaded chunks",
   "type": "stat",
   "description": "Total uploaded chunks",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(beekeeper_simulation_retrieval_chunks_uploaded_count{run=~\"$run\",node=~\"$node\"}[$__range]))"
    }
   ]
  },
  {
   "title": "not uploaded chunks",
   "type": "stat",
   "description": "Total not uploaded chunks",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(beekeeper_simulation_retrieval_chunks_not_uploaded_count{run=~\"$run\",node=~\"$node\"}[$__range]))"
    }
   ]
  },
  {
   "title": "synced chunks",
   "type": "stat",
   "description": "Total synced chunks",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(beekeeper_simulation_retrieval_tags_synced_count{run=~\"$run\",node=~\"$node\"}[$__range]))"
    }
   ]
  },
  {
   "title": "not synced chunks",
   "type": "stat",
   "description": "Total not synced chunks",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(beekeeper_simulation_retrieval_tags_not_synced_count{run=~\"$run\",node=~\"$node\"}[$__range]))"
    }
   ]
  },
  {
   "title": "downloaded chunks",
   "type": "stat",
   "description": "Total downloaded chunks",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(beekeeper_simulation_retrieval_chunks_downloaded_count{run=~\"$run\",node=~\"$node\"}[$__range]))"
    }
   ]
  },
  {
   "title": "not downloaded chunks",
   "type": "stat",
   "description": "Total not downloaded chunks",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(beekeeper_simulation_retrieval_chunks_not_downloaded_count{run=~\"$run\",node=~\"$node\"}[$__range]))"
    }
   ]
  },
  {
   "title": "correctly downloaded chunks",
   "type": "stat",
   "description": "Total correctly downloaded chunks",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(beekeeper_simulation_retrieval_chunks_retrieved_count{run=~\"$run\",node=~\"$node\"}[$__range]))"
    }
   ]
  },
  {
   "title": "incorrectly downloaded chunks",
   "type": "stat",
   "description": "Total incorrectly downloaded chunks",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(beekeeper_simulation_retrieval_chunks_not_retrieved_count{run=~\"$run\",node=~\"$node\"}[$__range]))"
    }
   ]
  },
  {
   "title": "upload rate",
   "type": "timeseries",
   "description": "Chunk upload rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "targets": [
    {
     "expr": "increase(beekeeper_simulation_retrieval_chunks_uploaded_count{run=~\"$run\",node=~\"$node\"}[$resolution])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "failed upload rate",
   "type": "timeseries",
   "description": "Chunk failed upload rate",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "targets": [
    {
     "expr": "increase(beekeeper_simulation_retrieval_chunks_not_uploaded_count{run=~\"$run\",node=~\"$node\"}[$resolution])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "sync rate",
   "type": "timeseries",
   "description": "Chunk sync rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
   "targets": [
    {
     "expr": "increase(beekeeper_simulation_retrieval_tags_synced_count{run=~\"$run\",node=~\"$node\"}[$resolution])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "failed sync rate",
   "type": "timeseries",
   "description": "Chunk failed sync rate",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
   "targets": [
    {
     "expr": "increase(beekeeper_simulation_retrieval_tags_not_synced_count{run=~\"$run\",node=~\"$node\"}[$resolution])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "download rate",
   "type": "timeseries",
   "description": "Chunk download rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 130 },
   "targets": [
    {
     "expr": "increase(beekeeper_simulation_retrieval_chunks_downloaded_count{run=~\"$run\",node=~\"$node\"}[$resolution])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "failed download rate",
   "type": "timeseries",
   "description": "Chunk failed download rate",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 130 },
   "targets": [
    {
     "expr": "increase(beekeeper_simulation_retrieval_chunks_not_downloaded_count{run=~\"$run\",node=~\"$node\"}[$resolution])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "correct  download rate",
   "type": "timeseries",
   "description": "Correct chunk download rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 138 },
   "targets": [
    {
     "expr": "increase(beekeeper_simulation_retrieval_chunks_retrieved_count{run=~\"$run\",node=~\"$node\"}[$resolution])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "incorrect download rate",
   "type": "timeseries",
   "description": "Incorrect chunk download rate",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 138 },
   "targets": [
    {
     "expr": "increase(beekeeper_simulation_retrieval_chunks_not_retrieved_count{run=~\"$run\",node=~\"$node\"}[$resolution])",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}