{
 "title": "SLA",
 "tags": [ "beekeeper" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(bee_info, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(bee_info{cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "instance",
    "query": "label_values(bee_info{cluster=~\"$cluster\", namespace=~\"$namespace\"}, instance)"
   },
   {
    "name": "interval",
    "query": "1m,5m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Network Availability", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "24h Upload Success",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(beekeeper_net_avail_upload_attempts[24h])-increase(beekeeper_net_avail_upload_errors_count[24h]))/increase(beekeeper_net_avail_upload_attempts[24h])"
    }
   ]
  },
  {
   "title": "24h Upload Success",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(beekeeper_net_avail_download_attempts[24h])-increase(beekeeper_net_avail_download_errors_count[24h]))/increase(beekeeper_net_avail_download_attempts[24h])"
    }
   ]
  },
  {
   "title": "All Time Upload Success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(beekeeper_net_avail_upload_attempts-beekeeper_net_avail_upload_errors_count)/beekeeper_net_avail_upload_attempts"
    }
   ]
  },
  {
   "title": "All Time Download Success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(beekeeper_net_avail_download_attempts-beekeeper_net_avail_download_errors_count)/beekeeper_net_avail_download_attempts"
    }
   ]
  },
  { "title": "Data Durability", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 17 } },
  {
   "title": "Avg chunk download duration",
   "type": "stat",
   "description": "Avg time taken to download a single chunk successfully",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(beekeeper_check_data_durability_chunk_download_duration_seconds_sum{job=\"$job\"}[$__range])/rate(beekeeper_check_data_durability_chunk_download_duration_seconds_count{job=\"$job\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg file download duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(beekeeper_check_data_durability_file_download_duration_seconds_sum{job=\"$job\"}[$__range])/rate(beekeeper_check_data_durability_file_download_duration_seconds_count{job=\"$job\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chunk retrieval rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1.0-(sum(increase(beekeeper_check_data_durability_chunk_download_errors{job=\"$job\"}[$__range]))/sum(increase(beekeeper_check_data_durability_chunk_download_attempts{job=\"$job\"}[$__range])))",
     "legendFormat": "{{ref}}"
    }
   ]
  },
  {
   "title": "File retrieval rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1.0-(sum(increase(beekeeper_check_data_durability_file_download_errors{job=\"$job\"}[$__range]))/sum(increase(beekeeper_check_data_durability_file_download_attempts{job=\"$job\"}[$__range])))",
     "legendFormat": "{{ref}}"
    }
   ]
  },
  {
   "title": "Total chunks in file",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beekeeper_check_data_durability_chunks_count{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total data downloaded",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(beekeeper_check_data_durability_file_size_bytes{job=\"$job\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\".+beekeeper-durability.+\",container=\"beekeeper\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chunk download attempts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(beekeeper_check_data_durability_chunk_download_attempts{job=\"$job\"}[$__range]))",
     "legendFormat": "{{ref}}"
    }
   ]
  },
  {
   "title": "Chunk download errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(beekeeper_check_data_durability_chunk_download_errors{job=\"$job\"}[$__range]))",
     "legendFormat": "{{ref}}"
    }
   ]
  },
  { "title": "Retrieval Latency", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 12, "y": 58 } },
  {
   "title": "24h Chunk Retrieval Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(beekeeper_net_avail_data_download_duration_sum{success=\"true\"}[$interval])/increase(beekeeper_net_avail_data_download_duration_count{success=\"true\"}[$interval])"
    }
   ]
  },
  {
   "title": "All Time Chunk Retrieval Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "beekeeper_net_avail_data_download_duration_sum{success=\"true\"}/beekeeper_net_avail_data_download_duration_count{success=\"true\"}"
    }
   ]
  },
  {
   "title": "24 hour average file download speed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beekeeper_check_longavailability_d_download_size_bytes/(rate(beekeeper_check_longavailability_d_download_duration_seconds_sum{job=\"$job\"}[$interval])/rate(beekeeper_check_longavailability_d_download_duration_seconds_count{job=\"$job\"}[$interval]))",
     "legendFormat": "{{ref}}"
    }
   ]
  },
  {
   "title": "All time file average download speed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beekeeper_check_longavailability_d_download_size_bytes/(beekeeper_check_longavailability_d_download_duration_seconds_sum{job=\"$job\"}/beekeeper_check_longavailability_d_download_duration_seconds_count{job=\"$job\"})",
     "legendFormat": "{{ref}}"
    }
   ]
  }
 ]
}