{
 "title": "Bee",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(bee_info, namespace)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(bee_info{namespace=\"$namespace\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "libp2p created connection",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bee_libp2p_created_connection_count{namespace=~\"$namespace\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "libp2p handled connection",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bee_libp2p_handled_connection_count{namespace=~\"$namespace\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "uptime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - bee_process_start_time_seconds{namespace=\"$namespace\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "restarts",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 19, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{job=\"kube-state-metrics\", cluster=\"\", namespace=\"$namespace\", pod=~\"$instance\", container=~\"bee\"}"
    }
   ]
  },
  {
   "title": "bee version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "bee_info{namespace=\"$namespace\",instance=~\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "go version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "go_info{namespace=\"$namespace\",instance=~\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "log messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_log_log_trace_count{namespace=\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "traces ({{pod}})"
    },
    {
     "expr": "increase(bee_log_debug_count{namespace=\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "debug ({{pod}})"
    },
    {
     "expr": "increase(bee_log_info_count{namespace=\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "info ({{pod}})"
    },
    {
     "expr": "increase(bee_log_warn_count{namespace=\"$namespace\", instance=\"$instance\"}[1m])",
     "legendFormat": "warn ({{pod}})"
    },
    {
     "expr": "increase(bee_log_error_count{namespace=\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "error ({{pod}})"
    }
   ]
  },
  {
   "title": "API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "api request rates",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(bee_api_ping_request_count{namespace=\"$namespace\", instance=~\"$instance\"}[1m])",
       "legendFormat": "api_ping_request_rate ({{pod}})"
      },
      {
       "expr": "increase(bee_api_request_count{namespace=\"$namespace\", instance=~\"$instance\"}[1m])",
       "legendFormat": "api_request_rate ({{pod}})"
      }
     ]
    },
    {
     "title": "response duration seconds",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "increase(bee_api_response_duration_seconds_bucket{namespace=\"$namespace\", instance=~\"$instance\"}[10m])",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "storage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"data-$instance\"}",
       "legendFormat": "used ({{persistentvolumeclaim}})"
      },
      {
       "expr": "kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"data-$instance\"}",
       "legendFormat": "total ({{persistentvolumeclaim}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "goroutines",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{namespace=\"$namespace\", instance=~\"$instance\"}",
       "legendFormat": "goroutines ({{pod}})"
      }
     ]
    },
    {
     "title": "memory usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_sys_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
       "legendFormat": "used ({{pod}})"
      },
      {
       "expr": "go_memstats_alloc_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
       "legendFormat": "allocated ({{pod}})"
      }
     ]
    },
    {
     "title": "gc cpu fraction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "go_memstats_gc_cpu_fraction{namespace=\"$namespace\", instance=~\"$instance\"}",
       "legendFormat": "({{pod}})"
      }
     ]
    },
    {
     "title": "gc rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "increase(go_gc_duration_seconds_count{namespace=\"$namespace\", instance=~\"$instance\"}[1m])",
       "legendFormat": "({{pod}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Accounting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "accounting",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(bee_accounting_accounting_blocks_count{namespace=\"$namespace\", instance=~\"$instance\"}[1m])",
       "legendFormat": "blocks ({{pod}})"
      },
      {
       "expr": "increase(bee_accounting_accounting_disconnects_count{namespace=\"$namespace\", instance=~\"$instance\"}[1m])",
       "legendFormat": "disconnects ({{pod}})"
      }
     ]
    },
    {
     "title": "events",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(bee_accounting_credit_events_count{namespace=\"$namespace\", instance=~\"$instance\"}[1m])",
       "legendFormat": "credit ({{pod}})"
      },
      {
       "expr": "increase(bee_accounting_debit_events_count{namespace=\"$namespace\", instance=~\"$instance\"}[1m])",
       "legendFormat": "debit ({{pod}})"
      }
     ]
    },
    {
     "title": "totals",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bee_accounting_total_credited_amount{namespace=\"$namespace\", instance=~\"$instance\"}",
       "legendFormat": "credited ({{pod}})"
      },
      {
       "expr": "bee_accounting_total_debited_amount{namespace=\"$namespace\", instance=~\"$instance\"}",
       "legendFormat": "debited ({{pod}})"
      }
     ]
    }
   ]
  }
 ]
}