{
 "title": "Bee - Kademlia",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(bee_info, namespace)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(bee_info{namespace=\"$namespace\"}, instance)"
   },
   { "name": "po", "label": "po", "query": "label_values(po)" }
  ]
 },
 "panels": [
  {
   "title": "Depth",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "bee_kademlia_current_depth{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "depth"
    }
   ]
  },
  {
   "title": "Radius",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "bee_kademlia_current_radius{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "depth"
    }
   ]
  },
  {
   "title": "Connect/Known",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "bee_kademlia_currently_connected_peers{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "connected"
    },
    {
     "expr": "bee_kademlia_currently_known_peers{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "known"
    }
   ]
  },
  {
   "title": "Current Depth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bee_kademlia_current_depth{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "depth"
    }
   ]
  },
  {
   "title": "Radius",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bee_kademlia_current_radius{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "radius"
    }
   ]
  },
  {
   "title": "Disconnects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_kademlia_total_inbound_disconnections{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "inbound"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_kademlia_total_inbound_connections{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "inbound"
    },
    {
     "expr": "increase(bee_kademlia_total_outbound_connections{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "outbound"
    }
   ]
  },
  {
   "title": "Libp2p blocklisting",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_libp2p_blocklisted_peer_count{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "blocklist event"
    }
   ]
  }
 ]
}