{
 "title": "Storage incentives - listener",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(bee_info, namespace)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(bee_info{namespace=\"$namespace\"}, instance)"
   },
   { "name": "po", "label": "po", "query": "label_values(po)" }
  ]
 },
 "panels": [
  {
   "title": "Backend calls",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "bee_postage_listener_backend_calls{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "available capacity (chunks)"
    }
   ]
  },
  {
   "title": "Backend errors",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "bee_postage_listener_backend_errors{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "radius"
    }
   ]
  },
  {
   "title": "Events",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(bee_postage_listener_created_events{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "created"
    },
    {
     "expr": "increase(bee_postage_listener_depth_events{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "dilution"
    },
    {
     "expr": "increase(bee_postage_listener_price_events{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "price change"
    },
    {
     "expr": "increase(bee_postage_listener_topup_events{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "topup"
    }
   ]
  },
  {
   "title": "events processed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_postage_listener_events_processed{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "events"
    }
   ]
  },
  {
   "title": "Pages processed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_postage_listener_pages_processed{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])  ",
     "legendFormat": "pages"
    }
   ]
  },
  {
   "title": "Event processing time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "increase(bee_postage_listener_event_duration{namespace=~\"$namespace\", instance=~\"$instance\"}[5m])",
     "legendFormat": "time"
    }
   ]
  }
 ]
}