{
 "title": "Bee - Localstore",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(bee_info, namespace)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(bee_info{namespace=\"$namespace\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Reserve and cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "reserve size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "bee_localstore_reserve_size{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "gc size",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_localstore_gc_size{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "reserve size growth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(bee_localstore_reserve_size{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])*4096",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "gc size growth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(bee_localstore_gc_size{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])*4096",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Timings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "GET time (avg/ch)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(bee_localstore_get_chunk_time{instance=~\"$instance\",namespace=~\"$namespace\"}[1m])/increase(bee_localstore_mode_get_count{instance=~\"$instance\",namespace=~\"$namespace\"}[1m])",
     "legendFormat": "time per chunk"
    }
   ]
  },
  {
   "title": "HAS time (avg/ch)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(bee_localstore_has_time{instance=~\"$instance\",namespace=~\"$namespace\"}[1m])/increase(bee_localstore_mode_has_count{instance=~\"$instance\",namespace=~\"$namespace\"}[1m])",
     "legendFormat": "time per chunk"
    }
   ]
  },
  {
   "title": "SET time (avg/ch)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(bee_localstore_set_time{instance=~\"$instance\",namespace=~\"$namespace\"}[1m])/increase(bee_localstore_mode_set_count{instance=~\"$instance\",namespace=~\"$namespace\"}[1m])",
     "legendFormat": "time per chunk"
    }
   ]
  },
  {
   "title": "PUT time (avg/ch)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(bee_localstore_put_time{instance=~\"$instance\",namespace=~\"$namespace\"}[1m])/increase(bee_localstore_mode_put_count{instance=~\"$instance\",namespace=~\"$namespace\"}[1m])",
     "legendFormat": "time per chunk"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "subscribe pull count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(bee_localstore_subscribe_pull_count{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
       "legendFormat": "blocklisted_peers({{instance}})"
      }
     ]
    },
    {
     "title": "subscribe push count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(bee_localstore_subscribe_push_count{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
       "legendFormat": "count({{instance}})"
      }
     ]
    }
   ]
  },
  { "title": "GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "gc",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_localstore_gc_fail_count{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "error_count({{instance}})"
    },
    {
     "expr": "increase(bee_localstore_gc_count{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "runs_count({{instance}})"
    }
   ]
  },
  {
   "title": "gc collected count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_localstore_gc_collected_count{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "collected_count({{instance}})"
    }
   ]
  },
  {
   "title": "gc size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bee_localstore_gc_size{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "gc_size({{instance}})"
    }
   ]
  },
  {
   "title": "gc exclude count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_localstore_gc_exclude_count{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "runs({{instance}})"
    },
    {
     "expr": "increase(bee_localstore_gc_exclude_fail_count{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "errors({{instance}})"
    }
   ]
  },
  {
   "title": "gc exclude time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "bee_localstore_gc_exclude_index_time{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "time({{instance}})"
    }
   ]
  },
  {
   "title": "gc update count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(bee_localstore_gc_update_count{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "update_count({{instance}})"
    }
   ]
  },
  {
   "title": "gc time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "increase(bee_localstore_gc_time{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "gc_time({{instance}})"
    },
    {
     "expr": "increase(bee_localstore_gc_lock_time{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "gc_lock_time({{instance}})"
    },
    {
     "expr": "increase(bee_localstore_gc_first_item_time{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "gc_first_item_time({{instance}})"
    }
   ]
  },
  {
   "title": "last gc timestamp",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_localstore_gc_time_stamp{namespace=~\"$namespace\", instance=~\"$instance\"}/1000000",
     "legendFormat": "blocklisted_peers({{instance}})"
    }
   ]
  },
  {
   "title": "gc time to first item",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_localstore_gc_first_item_time{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "time_to_first_item({{instance}})"
    }
   ]
  },
  {
   "title": "gc write batch error count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_localstore_gc_write_batch_error_count{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "blocklisted_peers({{instance}})"
    }
   ]
  }
 ]
}