{
 "title": "Bee Protocols",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(bee_info, namespace)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(bee_info{namespace=\"$namespace\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Pull sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "chunks offered/wanted/delivered",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_pullsync_chunks_delivered{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "delivered({{instance}})"
    },
    {
     "expr": "increase(bee_pullsync_chunks_offered{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "offered({{instance}})"
    },
    {
     "expr": "increase(bee_pullsync_chunks_wanted{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "wanted({{instance}})"
    }
   ]
  },
  {
   "title": "db ops",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_pullsync_db_ops{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "db ops({{instance}})"
    }
   ]
  },
  { "title": "Push sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "errors / received / sent",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_pushsync_total_errors{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "total_errors({{instance}})"
    },
    {
     "expr": "increase(bee_pushsync_total_received{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "total_received({{instance}})"
    },
    {
     "expr": "increase(bee_pushsync_total_sent{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "total_sent({{instance}})"
    }
   ]
  },
  { "title": "Pusher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "errors / synced / to push",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_pusher_total_errors{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "total_errors({{instance}})"
    },
    {
     "expr": "increase(bee_pusher_total_synced{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "total_synced({{instance}})"
    },
    {
     "expr": "increase(bee_pusher_total_to_push{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "total_to_push({{instance}})"
    }
   ]
  },
  {
   "title": "pusher sync time",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum(rate(bee_pusher_sync_time_bucket{namespace=~\"$namespace\", instance=~\"$instance\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "pusher error time",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "sum(rate(bee_pusher_error_time_bucket{namespace=~\"$namespace\", instance=~\"$instance\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "pusher mark sweep time",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum(rate(bee_pusher_mark_and_sweep_time_bucket{namespace=~\"$namespace\", instance=~\"$instance\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}