{
 "title": "Bee Pushsync",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(bee_info, namespace)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(bee_info{namespace=\"$namespace\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Sending", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "push to peer timer by bin - success",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(bee_pushsync_push_peer_time_sum{namespace=~\"$namespace\", instance=~\"$instance\", attempted=\"true\", status=\"success\"} / bee_pushsync_push_peer_time_count{namespace=~\"$namespace\", instance=~\"$instance\", attempted=\"true\", status=\"success\"}) by (bin)",
     "legendFormat": "{{bin}}"
    }
   ]
  },
  {
   "title": "push to peer timer by bin - failure",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(bee_pushsync_push_peer_time_sum{namespace=~\"$namespace\", instance=~\"$instance\", attempted=\"true\", status=\"failure\"} / bee_pushsync_push_peer_time_count{namespace=~\"$namespace\", instance=~\"$instance\", attempted=\"true\", status=\"failure\"}) by (bin)",
     "legendFormat": "{{bin}}"
    }
   ]
  },
  {
   "title": "send attempts, errors",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_pushsync_total_send_attempts{namespace=~\"$namespace\", instance=~\"$instance\"}[5m])",
     "legendFormat": "sent {{instance}}"
    },
    {
     "expr": "increase(bee_pushsync_total_failed_send_attempts{namespace=~\"$namespace\", instance=~\"$instance\"}[5m])",
     "legendFormat": "error {{instance}}"
    }
   ]
  },
  {
   "title": "Neighborhood Replication Error %",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_pushsync_total_replication_error{namespace=~\"$namespace\", instance=~\"$instance\"} / bee_pushsync_total_replication_attempts{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pusher - Outgoing Errors %",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 5, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_pushsync_total_outgoing_errors{namespace=~\"$namespace\", instance=~\"$instance\"} / bee_pushsync_total_outgoing{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "send error rate %",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 11, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_pushsync_total_failed_send_attempts{namespace=~\"$namespace\", instance=~\"$instance\"}/bee_pushsync_total_send_attempts{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "total_errors({{instance}})"
    }
   ]
  },
  { "title": "Receiving", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "received chunks / errors",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_pushsync_total_received{namespace=~\"$namespace\", instance=~\"$instance\"}[1h])",
     "legendFormat": "received {{instance}}"
    },
    {
     "expr": "increase(bee_pushsync_total_handler_errors{namespace=~\"$namespace\", instance=~\"$instance\"}[1h])",
     "legendFormat": "error {{instance}}"
    }
   ]
  },
  {
   "title": "Handler Time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Sec" }
   ],
   "targets": [
    {
     "expr": "bee_pushsync_total_handler_time_sum{namespace=~\"$namespace\", instance=~\"$instance\", status=\"failure\"}/bee_pushsync_total_handler_time_count{namespace=~\"$namespace\", instance=~\"$instance\", status=\"failure\"}",
     "legendFormat": "failure {{instance}}"
    },
    {
     "expr": "bee_pushsync_total_handler_time_sum{namespace=~\"$namespace\", instance=~\"$instance\", status=\"success\"}/bee_pushsync_total_handler_time_count{namespace=~\"$namespace\", instance=~\"$instance\", status=\"success\"}",
     "legendFormat": "success {{instance}}"
    }
   ]
  },
  {
   "title": "received, storer, forwarder counters",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_pushsync_total_received{namespace=~\"$namespace\", instance=~\"$instance\"}[1h])",
     "legendFormat": "Received {{instance}}"
    },
    {
     "expr": "increase(bee_pushsync_storer{namespace=~\"$namespace\", instance=~\"$instance\"}[1h])",
     "legendFormat": "Storer {{instance}}"
    },
    {
     "expr": "increase(bee_pushsync_forwarder{namespace=~\"$namespace\", instance=~\"$instance\"}[1h])",
     "legendFormat": "Forwarder {{instance}}"
    }
   ]
  },
  {
   "title": "Forwarder %",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_pushsync_forwarder{namespace=~\"$namespace\", instance=~\"$instance\"} / bee_pushsync_total_received{namespace=~\"$namespace\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Storer %",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_pushsync_storer{namespace=~\"$namespace\", instance=~\"$instance\"} / bee_pushsync_total_received{namespace=~\"$namespace\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Handler Replication Error %",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(bee_pushsync_handler_replication_errors{namespace=~\"$namespace\", instance=~\"$instance\"}) / (bee_pushsync_handler_replication{namespace=~\"$namespace\", instance=~\"$instance\"}) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Invalid Stamps  %",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(bee_pushsync_invalid_stamps{namespace=~\"$namespace\", instance=~\"$instance\"}) / (bee_pushsync_handler_replication{namespace=~\"$namespace\", instance=~\"$instance\"} + bee_pushsync_storer{namespace=~\"$namespace\", instance=~\"$instance\"} + bee_pushsync_forwarder{namespace=~\"$namespace\", instance=~\"$instance\"}) ",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}