{
increase_beekeeper_simulation_retrieval_chunk_download_seconds_bucket:{query:"increase(beekeeper_simulation_retrieval_chunk_download_seconds_bucket{run=~\"$run\"}[$resolution])",legend:"{{ le }}"},
increase_beekeeper_simulation_retrieval_chunk_upload_seconds_bucket:{query:"increase(beekeeper_simulation_retrieval_chunk_upload_seconds_bucket{run=~\"$run\"}[$resolution])",legend:"{{ le }}"},
increase_beekeeper_simulation_retrieval_chunks_downloaded_count:{query:"increase(beekeeper_simulation_retrieval_chunks_downloaded_count{run=~\"$run\",node=~\"$node\"}[$resolution])",legend:"{{node}}"},
increase_beekeeper_simulation_retrieval_chunks_not_downloaded_count:{query:"increase(beekeeper_simulation_retrieval_chunks_not_downloaded_count{run=~\"$run\",node=~\"$node\"}[$resolution])",legend:"{{node}}"},
increase_beekeeper_simulation_retrieval_chunks_not_retrieved_count:{query:"increase(beekeeper_simulation_retrieval_chunks_not_retrieved_count{run=~\"$run\",node=~\"$node\"}[$resolution])",legend:"{{node}}"},
increase_beekeeper_simulation_retrieval_chunks_not_uploaded_count:{query:"increase(beekeeper_simulation_retrieval_chunks_not_uploaded_count{run=~\"$run\",node=~\"$node\"}[$resolution])",legend:"{{node}}"},
increase_beekeeper_simulation_retrieval_chunks_retrieved_count:{query:"increase(beekeeper_simulation_retrieval_chunks_retrieved_count{run=~\"$run\",node=~\"$node\"}[$resolution])",legend:"{{node}}"},
increase_beekeeper_simulation_retrieval_chunks_uploaded_count:{query:"increase(beekeeper_simulation_retrieval_chunks_uploaded_count{run=~\"$run\",node=~\"$node\"}[$resolution])",legend:"{{node}}"},
increase_beekeeper_simulation_retrieval_tags_not_synced_count:{query:"increase(beekeeper_simulation_retrieval_tags_not_synced_count{run=~\"$run\",node=~\"$node\"}[$resolution])",legend:"{{node}}"},
increase_beekeeper_simulation_retrieval_tags_sync_seconds_bucket:{query:"increase(beekeeper_simulation_retrieval_tags_sync_seconds_bucket{run=~\"$run\"}[$resolution])",legend:"{{ le }}"},
increase_beekeeper_simulation_retrieval_tags_synced_count:{query:"increase(beekeeper_simulation_retrieval_tags_synced_count{run=~\"$run\",node=~\"$node\"}[$resolution])",legend:"{{node}}"},
sum_increase_beekeeper_simulation_retrieval_chunks_downloaded_count:{query:"sum(increase(beekeeper_simulation_retrieval_chunks_downloaded_count{run=~\"$run\",node=~\"$node\"}[$__range]))",legend:""},
sum_increase_beekeeper_simulation_retrieval_chunks_not_downloaded_count:{query:"sum(increase(beekeeper_simulation_retrieval_chunks_not_downloaded_count{run=~\"$run\",node=~\"$node\"}[$__range]))",legend:""},
sum_increase_beekeeper_simulation_retrieval_chunks_not_retrieved_count:{query:"sum(increase(beekeeper_simulation_retrieval_chunks_not_retrieved_count{run=~\"$run\",node=~\"$node\"}[$__range]))",legend:""},
sum_increase_beekeeper_simulation_retrieval_chunks_not_uploaded_count:{query:"sum(increase(beekeeper_simulation_retrieval_chunks_not_uploaded_count{run=~\"$run\",node=~\"$node\"}[$__range]))",legend:""},
sum_increase_beekeeper_simulation_retrieval_chunks_retrieved_count:{query:"sum(increase(beekeeper_simulation_retrieval_chunks_retrieved_count{run=~\"$run\",node=~\"$node\"}[$__range]))",legend:""},
sum_increase_beekeeper_simulation_retrieval_chunks_uploaded_count:{query:"sum(increase(beekeeper_simulation_retrieval_chunks_uploaded_count{run=~\"$run\",node=~\"$node\"}[$__range]))",legend:""},
sum_increase_beekeeper_simulation_retrieval_tags_not_synced_count:{query:"sum(increase(beekeeper_simulation_retrieval_tags_not_synced_count{run=~\"$run\",node=~\"$node\"}[$__range]))",legend:""},
sum_increase_beekeeper_simulation_retrieval_tags_synced_count:{query:"sum(increase(beekeeper_simulation_retrieval_tags_synced_count{run=~\"$run\",node=~\"$node\"}[$__range]))",legend:""},
}
