{
 "title": "Accounting",
 "tags": [ "components" ],
 "time": { "from": "2022-05-25T07:38:14.293Z", "to": "2022-05-25T07:42:22.131Z" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(bee_info, namespace)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(bee_info{namespace=\"$namespace\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "events",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_accounting_credit_events_count{namespace=\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "credit ({{pod}})"
    },
    {
     "expr": "increase(bee_accounting_debit_events_count{namespace=\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "debit ({{pod}})"
    }
   ]
  },
  {
   "title": "totals",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_accounting_total_credited_amount{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "credited ({{pod}})"
    },
    {
     "expr": "bee_accounting_total_debited_amount{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "debited ({{pod}})"
    }
   ]
  },
  {
   "title": "available balance",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "currencyBTC" }
   ],
   "targets": [
    {
     "expr": "bee_swap_available_balance{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "accounting",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_accounting_accounting_blocks_count{namespace=\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "blocks ({{pod}})"
    },
    {
     "expr": "increase(bee_accounting_accounting_disconnects_count{namespace=\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "disconnects ({{pod}})"
    }
   ]
  },
  {
   "title": "disconnects_reconnect_count",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_accounting_disconnects_reconnect_count{namespace=\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "debit ({{pod}})"
    }
   ]
  },
  {
   "title": "disconnects_enforce_refresh_count",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_accounting_disconnects_enforce_refresh_count{namespace=\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "credit ({{pod}})"
    }
   ]
  },
  {
   "title": "ghost_overdraw_count",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_accounting_disconnects_ghost_overdraw_count{namespace=\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "debit ({{pod}})"
    }
   ]
  },
  {
   "title": "disconnects_overdraw_count",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_accounting_disconnects_overdraw_count{namespace=\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "debit ({{pod}})"
    }
   ]
  },
  {
   "title": "refreshment_below_expected",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_accounting_refreshment_below_expected{namespace=\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "debit ({{pod}})"
    }
   ]
  },
  {
   "title": "refreshment_above_expected",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_accounting_refreshment_above_expected{namespace=\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "debit ({{pod}})"
    }
   ]
  },
  {
   "title": "time_out_of_sync_recent",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_accounting_time_out_of_sync_recent{namespace=\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "debit ({{pod}})"
    }
   ]
  },
  {
   "title": "time_out_of_sync_interval",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_accounting_time_out_of_sync_interval{namespace=\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "debit ({{pod}})"
    }
   ]
  },
  {
   "title": "time_out_of_sync_alleged",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_accounting_time_out_of_sync_alleged{namespace=\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "debit ({{pod}})"
    }
   ]
  }
 ]
}