{
 "title": "Bee (Namespace)",
 "tags": [ "components" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(bee_info, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Headlines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "libp2p created connection per bee node",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(bee_libp2p_created_connection_count{namespace=\"$namespace\"})/count(bee_libp2p_created_connection_count{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "libp2p handled connection per bee node",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(bee_libp2p_handled_connection_count{namespace=\"$namespace\"})/count(bee_libp2p_handled_connection_count{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "average uptime per bee node",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(time() - bee_process_start_time_seconds{namespace=\"$namespace\"})/count(bee_process_start_time_seconds{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "average restarts per bee node",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"$namespace\", container=\"bee\"})/count(kube_pod_container_status_restarts_total{namespace=\"$namespace\", container=\"bee\"})"
    }
   ]
  },
  {
   "title": "bee version (bee-0)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "bee_info{namespace=\"$namespace\",pod=\"bee-0\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "go version (bee-0)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_info{namespace=\"$namespace\",pod=\"bee-0\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "error logs increase over 1h",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_log_error_count{namespace=\"$namespace\"}[1h])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(bee_log_trace_count{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(bee_log_debug_count{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(bee_log_info_count{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(bee_log_warn_count{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(bee_log_error_count{namespace=\"$namespace\"}) by (pod)"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "cpu",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "cpu",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"}) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"}) by (pod) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\"}) by (pod)"
    }
   ]
  },
  {
   "title": "memory w/o cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", image!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "memory",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",container!=\"\", image!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",container!=\"\", image!=\"\"}) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",container!=\"\", image!=\"\"}) by (pod) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_rss{namespace=\"$namespace\",container!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_cache{namespace=\"$namespace\",container!=\"\"}) by (pod)"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "api requests increase over 1h",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_api_request_count{namespace=\"$namespace\"}[1h])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "api",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "sum(bee_api_response_duration_seconds_sum{namespace=\"$namespace\"}) by (pod) / sum(bee_api_response_duration_seconds_count{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(bee_api_request_count{namespace=\"$namespace\"}) by (pod)"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "storage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{namespace=\"$namespace\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "storage",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_available_bytes{namespace=\"$namespace\"}) by (persistentvolumeclaim)"
    },
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{namespace=\"$namespace\"}) by (persistentvolumeclaim)"
    },
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"}) by (persistentvolumeclaim)"
    }
   ]
  },
  { "title": "Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "goroutines increase over 1h",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(go_goroutines{namespace=\"$namespace\"}[1h])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "gc cpu fraction increase over 1h",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(go_memstats_gc_cpu_fraction{namespace=\"$namespace\"}[1h])",
     "legendFormat": "({{pod}})"
    }
   ]
  },
  {
   "title": "runtime",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 106 },
   "targets": [
    {
     "expr": "sum(go_goroutines{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(go_memstats_gc_cpu_fraction{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(go_gc_duration_seconds_count{namespace=\"$namespace\"}) by (pod)"
    }
   ]
  },
  { "title": "Accounting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 } },
  {
   "title": "accounting blocks increase over 1h",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_accounting_accounting_blocks_count{namespace=\"$namespace\"}[1h])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "accounting disconnects increase over 1h",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 123 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_accounting_accounting_disconnects_count{namespace=\"$namespace\"}[1h])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "accounting",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 131 },
   "targets": [
    {
     "expr": "min(bee_swap_available_balance{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(bee_accounting_accounting_blocks_count{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(bee_accounting_accounting_disconnects_count{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(bee_accounting_credit_events_count{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(bee_accounting_debit_events_count{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(bee_accounting_total_credited_amount{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(bee_accounting_total_debited_amount{namespace=\"$namespace\"}) by (pod)"
    }
   ]
  },
  { "title": "Retrieval", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 139 } },
  {
   "title": "total retrieval errors increase over 1h",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 140 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_retrieval_total_errors{namespace=\"$namespace\"}[1h])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "retrieval",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 148 },
   "targets": [
    {
     "expr": "sum(bee_retrieval_total_retrieved{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(bee_retrieval_total_errors{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(bee_retrieval_peer_request_count{namespace=\"$namespace\"}) by (pod)\n-\nsum(bee_retrieval_request_count{namespace=\"$namespace\"}) by (pod)"
    }
   ]
  }
 ]
}