{
 "title": "Chain calls",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(bee_info, namespace)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(bee_info{namespace=\"$namespace\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total RPC calls",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bee_eth_backend_total_rpc_calls{namespace=~\"$namespace\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Calls to eth_blockNumber count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bee_eth_backend_calls_block_number{namespace=~\"$namespace\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "RPC calls",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_eth_backend_total_rpc_calls{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "blocklisted_peers({{instance}})"
    }
   ]
  },
  {
   "title": "Get Block Number calls",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_eth_backend_calls_block_number{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "disconnects({{instance}})"
    }
   ]
  }
 ]
}