{
 "title": "Faucet",
 "description": "Graph Ethereum and BZZ Wallet Balances with ease",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "name",
    "query": "label_values(eth_balance, name)"
   },
   {
    "name": "token",
    "label": "token",
    "query": "label_values(token_balance, symbol)"
   }
  ]
 },
 "panels": [
  {
   "title": "gETH balance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "locale", "label": "gETH" }
   ],
   "targets": [
    {
     "expr": "eth_balance{name=\"${name}\"}",
     "legendFormat": "${name} eth"
    }
   ]
  },
  {
   "title": "gETH",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "eth_balance{name=\"${name}\"}"
    }
   ]
  },
  {
   "title": "gETH 1 hour change",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(eth_balance{name=\"${name}\"} - eth_balance{name=\"${name}\"} offset 1h) / eth_balance{name=\"${name}\"}"
    }
   ]
  },
  {
   "title": "gETH 24 hour change",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(eth_balance{name=\"${name}\"} - eth_balance{name=\"${name}\"} offset 24h) / eth_balance{name=\"${name}\"}"
    }
   ]
  },
  {
   "title": "gETH week change",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(eth_balance{name=\"${name}\"} - eth_balance{name=\"${name}\"} offset 7d) / eth_balance{name=\"${name}\"}"
    }
   ]
  },
  {
   "title": "${token} balance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "locale", "label": "gBZZ" }
   ],
   "targets": [
    {
     "expr": "token_balance{name=\"${name}\",symbol=\"${token}\"}",
     "legendFormat": "${name} ${token}"
    }
   ]
  },
  {
   "title": "${token}",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 8 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "token_balance{name=\"${name}\",symbol=\"gBZZ\"}"
    }
   ]
  },
  {
   "title": "${token} 1 hour change",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(token_balance{name=\"${name}\",symbol=\"gBZZ\"} - token_balance{name=\"${name}\",symbol=\"gBZZ\"} offset 1h) / token_balance{name=\"${name}\",symbol=\"gBZZ\"}"
    }
   ]
  },
  {
   "title": "${token} 24 hour change",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(token_balance{name=\"${name}\",symbol=\"gBZZ\"} - token_balance{name=\"${name}\",symbol=\"gBZZ\"} offset 24h) / token_balance{name=\"${name}\",symbol=\"gBZZ\"}"
    }
   ]
  },
  {
   "title": "${token} 1 week change",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(token_balance{name=\"${name}\",symbol=\"gBZZ\"} - token_balance{name=\"${name}\",symbol=\"gBZZ\"} offset 7d) / token_balance{name=\"${name}\",symbol=\"gBZZ\"}"
    }
   ]
  }
 ]
}