{
 "title": "Localstore",
 "tags": [ "components" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(bee_info, namespace)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(bee_info{namespace=\"$namespace\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Sizes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Reserve size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "bee_localstore_reserve_size{instance=~\"$instance\", namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cache size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "bee_localstore_cache_size{instance=~\"$instance\", namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Evictions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Storage Radius",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "bee_localstore_storage_radius{instance=~\"$instance\", namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Over capacity triggers (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(bee_localstore_over_cap_trigger_count{instance=~\"$instance\", namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Eviction count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "bee_localstore_evicted_count{instance=~\"$instance\", namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Expiration count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "bee_localstore_expired_count{instance=~\"$instance\", namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Eviction rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(bee_localstore_evicted_count{instance=~\"$instance\", namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Expiration rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "rate(bee_localstore_expired_count{instance=~\"$instance\", namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Expired batches processed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_localstore_expired_batch_count{instance=~\"$instance\", namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "TX Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(bee_storage_tx_total_duration_sum{instance=~\"$instance\", namespace=~\"$namespace\"}[5m]))\r\n/\r\nsum(increase(bee_storage_tx_total_duration_count{instance=~\"$instance\", namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Reserve Component Methods Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(bee_localstore_method_calls_duration_sum{instance=~\"$instance\", namespace=~\"$namespace\", component=\"reserve\"}[5m])) by (method)\r\n/\r\nsum(increase(bee_localstore_method_calls_duration_count{instance=~\"$instance\", namespace=~\"$namespace\", component=\"reserve\"}[5m])) by (method)\r\n",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Reserve Component Methods Call Error Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bee_localstore_method_calls{instance=~\"$instance\", namespace=~\"$namespace\", component=\"reserve\", status=\"failure\"}) by (method) / sum(bee_localstore_method_calls{instance=~\"$instance\", namespace=~\"$namespace\", component=\"reserve\"}) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Indexstore Component Methods Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(bee_storage_index_store_calls_duration_sum{instance=~\"$instance\", namespace=~\"$namespace\"}[5m])) by (method)\r\n/\r\nsum(increase(bee_storage_index_store_calls_duration_count{instance=~\"$instance\", namespace=~\"$namespace\"}[5m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexstore Component Methods Call Error Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bee_storage_index_store_calls{instance=~\"$instance\", namespace=~\"$namespace\", status=\"failure\"}) by (method) / sum(bee_storage_index_store_calls{instance=~\"$instance\", namespace=~\"$namespace\"}) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Chunkstore Component Methods Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(bee_storage_chunk_store_calls_duration_sum{instance=~\"$instance\", namespace=~\"$namespace\"}[5m])) by (method)\r\n/\r\nsum(increase(bee_storage_chunk_store_calls_duration_count{instance=~\"$instance\", namespace=~\"$namespace\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Chunkstore Component Methods Call Error Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bee_storage_chunk_store_calls{instance=~\"$instance\", namespace=~\"$namespace\", status=\"failure\"}) by (method) / sum(bee_storage_chunk_store_calls{instance=~\"$instance\", namespace=~\"$namespace\"}) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Cachestore Component Methods Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(bee_localstore_method_calls_duration_sum{instance=~\"$instance\", namespace=~\"$namespace\", component=\"cachestore\"}[5m])) by (method)\r\n/\r\nsum(increase(bee_localstore_method_calls_duration_count{instance=~\"$instance\", namespace=~\"$namespace\", component=\"cachestore\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Cachestore Component Methods Call Error Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bee_localstore_method_calls{instance=~\"$instance\", namespace=~\"$namespace\", component=\"cachestore\", status=\"failure\"}) by (method) / sum(bee_localstore_method_calls{instance=~\"$instance\", namespace=~\"$namespace\", component=\"cachestore\"}) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Netstore Component Methods Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(bee_localstore_method_calls_duration_sum{instance=~\"$instance\", namespace=~\"$namespace\", component=\"netstore\"}[5m])) by (method)\r\n/\r\nsum(increase(bee_localstore_method_calls_duration_count{instance=~\"$instance\", namespace=~\"$namespace\", component=\"netstore\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Netstore Component Methods Call Error Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bee_localstore_method_calls{instance=~\"$instance\", namespace=~\"$namespace\", component=\"netstore\", status=\"failure\"}) by (method) / sum(bee_localstore_method_calls{instance=~\"$instance\", namespace=~\"$namespace\", component=\"netstore\"}) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Pinstore Component Methods Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(bee_localstore_method_calls_duration_sum{instance=~\"$instance\", namespace=~\"$namespace\", component=\"pinstore\"}[5m])) by (method)\r\n/\r\nsum(increase(bee_localstore_method_calls_duration_count{instance=~\"$instance\", namespace=~\"$namespace\", component=\"pinstore\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Pinstore Component Methods Call Error Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bee_localstore_method_calls{instance=~\"$instance\", namespace=~\"$namespace\", component=\"pinstore\", status=\"failure\"}) by (method) / sum(bee_localstore_method_calls{instance=~\"$instance\", namespace=~\"$namespace\", component=\"pinstore\"}) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  { "title": "LevelDB Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "Write Delay Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{instance=~\"$instance\", namespace=~\"$namespace\", counter=\"write_delay_count\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Write Delay Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{instance=~\"$instance\", namespace=~\"$namespace\", counter=\"write_delay_duration\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Alive Snapshots",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{instance=~\"$instance\", namespace=~\"$namespace\", counter=\"alive_snapshots\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Alive Iterators",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{instance=~\"$instance\", namespace=~\"$namespace\", counter=\"alive_iterators\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "IO Read",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{instance=~\"$instance\", namespace=~\"$namespace\", counter=\"io_read\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "IO Write",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{instance=~\"$instance\", namespace=~\"$namespace\", counter=\"io_write\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Block Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{instance=~\"$instance\", namespace=~\"$namespace\", counter=\"block_cache_size\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Opened Tables",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{instance=~\"$instance\", namespace=~\"$namespace\", counter=\"opened_tables_count\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Compaction",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{instance=~\"$instance\", namespace=~\"$namespace\", counter=\"mem_comp\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Level 0 Compaction",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{instance=~\"$instance\", namespace=~\"$namespace\", counter=\"level_0_comp\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Non Level 0 Compaction",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{instance=~\"$instance\", namespace=~\"$namespace\", counter=\"non_level_0_comp\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Seek Compaction",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{instance=~\"$instance\", namespace=~\"$namespace\", counter=\"seek_comp\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Level Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{instance=~\"$instance\", namespace=~\"$namespace\", counter=\"level_0_size\"}[$__rate_interval])",
     "legendFormat": "{{pod}}->{{counter}}"
    },
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{instance=~\"$instance\", namespace=~\"$namespace\", counter=\"level_1_size\"}[$__rate_interval])",
     "legendFormat": "{{pod}}->{{counter}}"
    },
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{instance=~\"$instance\", namespace=~\"$namespace\", counter=\"level_2_size\"}[$__rate_interval])",
     "legendFormat": "{{pod}}->{{counter}}"
    }
   ]
  },
  {
   "title": "Table Count by Level",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{instance=~\"$instance\", namespace=~\"$namespace\", counter=\"level_0_tables_count\"}[$__rate_interval])",
     "legendFormat": "{{pod}}->{{counter}}"
    },
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{instance=~\"$instance\", namespace=~\"$namespace\", counter=\"level_1_tables_count\"}[$__rate_interval])",
     "legendFormat": "{{pod}}->{{counter}}"
    },
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{instance=~\"$instance\", namespace=~\"$namespace\", counter=\"level_2_tables_count\"}[$__rate_interval])",
     "legendFormat": "{{pod}}->{{counter}}"
    }
   ]
  },
  {
   "title": "Read by Level",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 162 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{instance=~\"$instance\", namespace=~\"$namespace\", counter=\"level_0_read\"}[$__rate_interval])",
     "legendFormat": "{{pod}}->{{counter}}"
    },
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{instance=~\"$instance\", namespace=~\"$namespace\", counter=\"level_1_read\"}[$__rate_interval])",
     "legendFormat": "{{pod}}->{{counter}}"
    },
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{instance=~\"$instance\", namespace=~\"$namespace\", counter=\"level_2_read\"}[$__rate_interval])",
     "legendFormat": "{{pod}}->{{counter}}"
    }
   ]
  },
  {
   "title": "Write by Level",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 162 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{instance=~\"$instance\", namespace=~\"$namespace\", counter=\"level_0_write\"}[$__rate_interval])",
     "legendFormat": "{{pod}}->{{counter}}"
    },
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{instance=~\"$instance\", namespace=~\"$namespace\", counter=\"level_1_write\"}[$__rate_interval])",
     "legendFormat": "{{pod}}->{{counter}}"
    },
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{instance=~\"$instance\", namespace=~\"$namespace\", counter=\"level_2_write\"}[$__rate_interval])",
     "legendFormat": "{{pod}}->{{counter}}"
    }
   ]
  },
  {
   "title": "Compaction Duration by Level",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{instance=~\"$instance\", namespace=~\"$namespace\", counter=\"level_0_duration\"}[$__rate_interval])",
     "legendFormat": "{{pod}}->{{counter}}"
    },
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{instance=~\"$instance\", namespace=~\"$namespace\", counter=\"level_1_duration\"}[$__rate_interval])",
     "legendFormat": "{{pod}}->{{counter}}"
    },
    {
     "expr": "increase(bee_localstore_leveldb_stats_sum{instance=~\"$instance\", namespace=~\"$namespace\", counter=\"level_2_duration\"}[$__rate_interval])",
     "legendFormat": "{{pod}}->{{counter}}"
    }
   ]
  }
 ]
}