{
 "title": "Streams",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(bee_info, namespace)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(bee_info{namespace=\"$namespace\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "libp2p created streams",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(bee_libp2p_created_stream_count{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "libp2p library reported created streams",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(bee_libp2p_library_reported_created_stream_count{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "libp2p stream reset count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(bee_stream_reset_count{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "libp2p closed stream count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(bee_libp2p_closed_stream_count{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "libp2p library reported closed stream count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(bee_libp2p_library_reported_closed_stream_count{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "libp2p handled stream count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(bee_libp2p_handled_stream_count{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "libp2p stream handler reset errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(bee_libp2p_stream_handler_error_reset_count{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "Incoming streams (handled vs errored)",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_libp2p_handled_stream_count{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "peers({{instance}})"
    },
    {
     "expr": "increase(bee_libp2p_stream_handler_error_reset_count{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "peers_err({{instance}})"
    }
   ]
  },
  {
   "title": "Incoming streams (handled vs errored)",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(bee_libp2p_stream_handler_error_reset_count{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])/increase(bee_libp2p_handled_stream_count{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "peers({{instance}})"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Created streams",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_libp2p_created_stream_count{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "peers({{instance}})"
    },
    {
     "expr": "increase(bee_libp2p_library_reported_created_stream_count{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "peers({{instance}})"
    }
   ]
  },
  {
   "title": "Closed streams",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_libp2p_closed_stream_count{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "disconnects({{instance}})"
    },
    {
     "expr": "increase(bee_libp2p_library_reported_closed_stream_count{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "connects({{instance}})"
    }
   ]
  }
 ]
}