{
 "title": "Handshake",
 "tags": [ "protocols" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(bee_info, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(bee_info{cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "instance",
    "query": "label_values(bee_info{cluster=~\"$cluster\", namespace=~\"$namespace\"}, instance)"
   },
   {
    "name": "interval",
    "query": "1m,5m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "SYN-ACK TX Fail Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-(bee_handshake_syn_ack_tx{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}-bee_handshake_syn_ack_tx_failed{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"})/bee_handshake_syn_ack_tx{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ACK RX Fail Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-(bee_handshake_ack_rx{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}-bee_handshake_ack_rx_failed{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"})/bee_handshake_ack_rx{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SYN RX Fail Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-(bee_handshake_syn_rx{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}-bee_handshake_syn_rx_failed{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"})/bee_handshake_syn_rx{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}"
    }
   ]
  }
 ]
}