{
 "title": "PushSync",
 "tags": [ "protocols" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(bee_info, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(bee_info{cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "instance",
    "query": "label_values(bee_info{cluster=~\"$cluster\", namespace=~\"$namespace\"}, instance)"
   },
   {
    "name": "interval",
    "query": "1m,5m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Sending", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "P95 Push to Peer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,sum(rate(bee_pushsync_push_peer_time_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval]))by(le,instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "send time - failure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(bee_pushsync_push_peer_time_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",status=\"failure\"}[$interval])/increase(bee_pushsync_push_peer_time_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",status=\"failure\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "send time - success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(bee_pushsync_push_peer_time_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",status=\"success\"}[$interval])/increase(bee_pushsync_push_peer_time_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",status=\"success\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Originator Error %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(bee_pushsync_total_outgoing_errors{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])/increase(bee_pushsync_total_outgoing{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "attempt error %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(bee_pushsync_total_failed_send_attempts{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])/increase(bee_pushsync_total_send_attempts{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "sends per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "rate(bee_pushsync_total_send_attempts{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "shallow receipt %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(bee_pusher_shallow_receipt{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])/(increase(bee_pushsync_total_outgoing{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])-increase(bee_pushsync_total_outgoing_errors{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Receipt Depths",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(bee_pusher_receipt_depth{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval]))by(depth)",
     "legendFormat": "{{depth}} {{instance}}"
    }
   ]
  },
  { "title": "Receiving", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 33 } },
  {
   "title": "incoming deliveries per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "rate(bee_pushsync_total_received{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "handler error %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(bee_pushsync_total_handler_errors{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])/increase(bee_pushsync_total_received{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Handler Time  - failure ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(bee_pushsync_total_handler_time_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",status=\"failure\"}[$interval])/increase(bee_pushsync_total_handler_time_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",status=\"failure\"}[$interval])",
     "legendFormat": "failure {{instance}}"
    }
   ]
  },
  {
   "title": "Handler Time  - success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(bee_pushsync_total_handler_time_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",status=\"success\"}[$interval])/increase(bee_pushsync_total_handler_time_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\",status=\"success\"}[$interval])",
     "legendFormat": "success {{instance}}"
    }
   ]
  },
  {
   "title": "Stamp Validation (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(bee_pushsync_stamp_validation_time_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval]))by(instance)/sum(increase(bee_pushsync_stamp_validation_time_count{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval]))by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Invalid Stamps  %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(bee_pushsync_invalid_stamps{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])/increase(bee_pushsync_total_received{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Forwarder %",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "inc(bee_pushsync_forwarder{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}/bee_pushsync_total_received{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Storer %",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increae(bee_pushsync_storer{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}/bee_pushsync_total_received{cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}"
    }
   ]
  }
 ]
}